### ISSUE TITLE
Add Unidata Motherlode forecast datasets

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog#10]
Unidata Motherlode was in the previous IOOS Catalog.  

Need to investigate metadata sources.  

@rsignell-usgs

**Comment by mwengren** [comment]
@rsignell-usgs WAF is empty at the moment.  

http://thredds.axiomdatascience.com/iso/unidata/

I believe this was the source for the Unidata forecasts.  Seems that Axiom would have to be consulted on the content.

**Comment by rsignell-usgs** [comment]
Yes, that's where they used to be.   Also there was this helpful WAF of NGDC met datasets also, now also empty:
http://thredds.axiomdatascience.com/iso/ndbc_stdmet/

@kwilcox, can we get these harvesters working again?  (or have the WAF folders just moved?)

**Comment by rsignell-usgs** [comment]
I was going to show Unidata that we were harvesting motherlode, but then was not able to do so.  :disappointed:

**Comment by kwilcox** [comment]
**Re: ndbc_stdmet**
ISO links stopped working: http://dods.ndbc.noaa.gov/thredds/catalog/data/stdmet/tshf1/catalog.html?dataset=data/stdmet/tshf1/tshf1h2010.nc

**Re: unidata**
A few datasets started throwing errors. I'll push a fix to thredds_crawler that will bypass these.

```
* Could not process http://thredds-jumbo.unidata.ucar.edu/thredds/catalog/grib/HRRR/CONUS_3km/surface/catalog.xml?dataset=grib/HRRR/CONUS_3km/surface/Best. No serviceName definition found!.
* Could not process http://thredds-jumbo.unidata.ucar.edu/thredds/catalog/grib/HRRR/CONUS_3km/wrfprs/catalog.xml?dataset=grib/HRRR/CONUS_3km/wrfprs/Best. No serviceName definition found!.
* Error procesing http://thredds.ucar.edu/thredds/catalog/grib/NCEP/NAM/Firewxnest/catalog.xml?dataset=grib/NCEP/NAM/Firewxnest/Best/LambertConformal_379X578-34p52N-118p2W, invalid XML
```

**Comment by mwengren** [comment]
Resolved via #87

**Comment by kwilcox** [comment]
What is #87?

**Comment by mwengren** [comment]
Sorry, wrote that from [here](https://waffle.io/ioos/catalog), forgot the different repo issue # issue, should have been ioos/catalog-ckan#87.

**Comment by kwilcox** [comment]
Thanks. Can I remove the WAF at http://thredds.axiomdatascience.com/iso/unidata/?

**Comment by mwengren** [comment]
Well, that depends.  If that's the same as http://thredds.axiomalaska.com/iso/unidata/, then no, because we're depending on that for the metadata source.  Otherwise, no problem.  At this point we're relying on you guys to harvest that server for metadata... https://registry.ioos.us/harvests/xXy1M2joVL8QQRoZq.

**Comment by kwilcox** [comment]
It is the same thing. I mistakenly didn't click https://dev-catalog.ioos.us/harvest/unidata-waf and assumed it was a WAF that the catalog started crawling and generating. We'll keep the Unidata WAF up indefinitely.

**Comment by mwengren** [comment]
Yeah, that's just a mirror of yours.  We could move it to data.ioos.us if necessary I imagine, I don't think it would be a problem, but stealing your script would help with that.  If you guys would rather not keep that dependency on your side, let's do that.

Actually, if you don't mind sharing, I'm trying to collect example THREDDS/ncISO WAF scripts [here](https://github.com/ioos/catalog/tree/master/waf_generation_scripts) in case people need inspiration to create their own.
