### ISSUE TITLE
Map needs query from mouse ability

### ISSUE THREAD

**Issue by daf** [ioos/catalog#15]
Currently the map is only movable/zoomable, it needs to be able to query points/polygons via the mouse/touch event.

In addition, thought needs to be applied to how to deal with multiple items at a single point.  My thought leads to an onion-skin style approach, similar to:

![](http://www.w3.org/TR/CSS21/images/tbl-layers.png)

This could be presented in the existing dataset query box or a different one to be able to select between them.

**Comment by kknee** [comment]
Fixed in version 3.2
