### ISSUE TITLE
Availability of a test/staging catalog (& registry)?

### ISSUE THREAD

**Issue by emiliom** [ioos/catalog#16]
My understanding is that the catalog system that's in development, https://dev-catalog.ioos.us, will become the live one (at different url) around next month.

@mwengren, will there be a system/version that remains as a parallel, testing version? That's a common approach that would be very helpful to enable metadata debugging and improvements based on the IOOS Catalog as the target, w/o having to expose those suboptimal metadata on a public, production system.

**Comment by mwengren** [comment]
@lukecampbell @kknee let's discuss estimated costs for running staging/qa Registry/Data Catalog/Service Monitor on an ongoing basis in a future meeting.  I agree it would be a good idea.   We may want to restrict access though, at least to the Data Catalog component to avoid confusion on what is production or not.

**Comment by benjwadams** [comment]
There is a dev catalog server, but it's presently only accessible via the external IP address.  I'll get it registered with DNS and see what we can do.

**Comment by benjwadams** [comment]
https://dev-catalog.ioos.us now points to an actual development version of the catalog.
