### ISSUE TITLE
Additional filtering for map

### ISSUE THREAD

**Issue by daf** [ioos/catalog#19]
Currently the only filter is RA (and it is mandatory).  Additional filters to provide:

- [ ] Variable
- [ ] Asset Type
- [ ] bbox
- [ ] timeframe

All filters should be capable of having multiple values, not just one.

**Comment by carmelortiz** [comment]
Related comment from Chris Ostrander via IOOS Catalog Feedback Form:
"Ideally there would be a way to filter between data from observations, and data from models (or other static data, like bathymetry).  It's difficult, if not impossible, to discover what assets a region is maintaining and has deployed from this system, since everything is turned on and available all the time."

**Comment by carmelortiz** [comment]
And another similar comment from Chris Ostrander via IOOS Catalog Feedback Form, related to filtering:
"Selecting by region is confusing.  Who's the customer?  Only inside-IOOS folks know what all the regional names mean, and someone wanting to search for data in various parts of the country won't have any clue how to decode 23 "region" options on the asset map, when IOOS states that there are only 11 regions, and none of the acronyms make it clear what geography is being selected."

**Comment by lukecampbell** [comment]
The bounding box may have to wait until we migrate to PostGIS. Making our current database support geospatial queries may be more work than we want to spend on it for this milestone when we get it for free down the road. The others are pretty straight forwad

**Comment by dpsnowden** [comment]
Agreed about not wasting time doing something that we'll get for free.  This begs the question of when the PostGIS migration happens within the current release plan.

Are we implementing a general faceted search strategy?  I understand the features described here but I don't understand how we're going to integrate it into the UI.

**Comment by benjwadams** [comment]
MongoDB does have basic geospatial query operators.  I got odd/incorrect results last time I tried the spatial operators, but maybe it'll be worth another go.

http://docs.mongodb.org/manual/reference/operator/query-geospatial/

**Comment by benjwadams** [comment]
Going to have to break these up into separate issues for maintanability reasons.

BBox may not be doable this time around.  Some of the content in GeoJSON needs to be cleaned up before we can apply a spatial index to do the querying.

**Comment by benjwadams** [comment]
Closing and splitting issues mentioned into #383, #384, #385, and #386.
