### ISSUE TITLE
Suggestion: Temporary caching if source WAF is down?

### ISSUE THREAD

**Issue by emiliom** [ioos/catalog#20]
We had a power outage yesterday that hit all our servers; the impact lasted <20 hours. But our WAF server must have been down when the registry/catalog did its daily reharvest (early in the morning?). That resulted in 0 metadata records for NANOOS being shown today on the IOOS Catalog. Our servers are back up, and I'm assuming everything will be peachy on the next harvest tomorrow.

So that made me think: would it make sense to have a policy (and corresponding implementation) of reusing the cached metadata if a WAF isn't found during the daily harvest, say, for two harvest cycles or so? I can see that there could be tricky ramifications to be worked out, but at the same time, the current set up also has extreme consequences: even a brief WAF server unavailability can result in a 24-hour catalog emptying out, if the unavailability happened to coincide with the harvesting timing.

It seems better to have slightly old metadata (for a given WAF) in the catalog, than no metadata records at all.

My 2 cents.

**Comment by rsignell-usgs** [comment]
I agree, and I think 3 days might be a good time period to cache the data if the WAF is unavailable.  That would allow enough time for it to go down Friday at COB and be fixed by Monday at COB.

**Comment by lukecampbell** [comment]
We've also heard the opposite request from providers that they want the data to be immediately removed when a source is either removed. Right now we keep the WAF data for 2 days, I believe, before it gets removed from the registry's WAF. I currently have a task to tighten the consistency between provider's WAFs and our publication. Maybe we need to curb that task and discuss further.

**Comment by emiliom** [comment]
@lukecampbell, I wouldn't characterize the request from providers you mention as "the opposite". I can definitely see the desirability of having the registry/catalog react quickly to *deliberate* choices made by the providers, such as removal of individual metadata records.

Maybe the distinction is between individual metadata records becoming unavailable (likely a deliberate choice) and an entire WAF or CSW endpoint becoming unavailable (likely a system problem)?

No doubt, there are tricky subtleties to be worked out.

> Right now we keep the WAF data for 2 days, I believe, before it gets removed from the registry's WAF.

FYI, I didn't see that behavior in my case. The catalog was flushed out to 0 records the same day the WAFs were first unavailable. And actually the catalog seemed to remain flushed out even 24 hours later (yesterday), when the WAFs had been back for about 24 hours. Though maybe I'd need more information about the exact timing of the registry/catalog harvesting -- I'm assuming it happens between midnight and dawn.

**Comment by lukecampbell** [comment]
Yeah, we had some scheduled work to reduce the time from 2 days to something smaller, that may have already happened. When I get back I'll look into this and probably reach out to you to work out some of the subtle use-cases.

**Comment by lukecampbell** [comment]
@emiliom this should be taken care of now.

**Comment by emiliom** [comment]
@lukecampbell, can you describe what's the "solution" or new configuration? I don't think that's obvious from the previous discussions back in early January. Unless the new set up is what's described in https://github.com/ioos/catalog-harvesting/issues/40 and https://github.com/ioos/catalog-harvesting/issues/45 from Jan 23? Thanks.
