### ISSUE TITLE
NULL feature type causes harvesting error

### ISSUE THREAD

**Issue by lukecampbell** [ioos/catalog#200]
```
Traceback (most recent call last):
  File "/home/monitoring/.virtualenvs/monitoring/lib/python2.7/site-packages/rq/worker.py", line 407, in perform_job
    rv = job.perform()
  File "/home/monitoring/.virtualenvs/monitoring/lib/python2.7/site-packages/rq/job.py", line 386, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/home/monitoring/ioos-service-monitor/ioos_catalog/tasks/debug.py", line 10, in wrapper
    return func(*args, **kwargs)
  File "/home/monitoring/ioos-service-monitor/ioos_catalog/tasks/harvest.py", line 74, in harvest
    return SosHarvest(service).harvest()
  File "/home/monitoring/ioos-service-monitor/ioos_catalog/tasks/harvest.py", line 206, in harvest
    self.sos = SensorObservationService(self.service.get('url'))
  File "/home/monitoring/.virtualenvs/monitoring/lib/python2.7/site-packages/owslib/sos.py", line 19, in SensorObservationService
    return sos100.SensorObservationService_1_0_0.__new__(sos100.SensorObservationService_1_0_0, url, version, xml)
  File "/home/monitoring/.virtualenvs/monitoring/lib/python2.7/site-packages/owslib/swe/observation/sos100.py", line 28, in __new__
    obj.__init__(url, version, xml, username, password)
  File "/home/monitoring/.virtualenvs/monitoring/lib/python2.7/site-packages/owslib/swe/observation/sos100.py", line 57, in __init__
    raise ows.ExceptionReport(self._capabilities)
ExceptionReport: "Unable to read the dataset's feature type. NULL dataset."
```

We should investigate it but this may not be something the catalog can solve.

**Comment by benjwadams** [comment]
> What we need to focus on with this is to capture and report the error messages better.

**Comment by lukecampbell** [comment]
I'm not 100% certain of this but 
https://github.com/ioos/catalog/blob/master/ioos_catalog/models/harvests.py#L94-95

I think if we add another except here that catches the SOS error and look for "NULL dataset"  then we'll translate the error message as "Invalid SOS response".

**Comment by dpsnowden** [comment]
"Invalid SOS response" doesn't sound any more descriptive if the aim is to give the data provider clear guidance on what element in their SOS needs fixing. Can we be more descriptive? What call generated the exception? Getcap? DescribeSensor? What XML element is wrong?

**Comment by benjwadams** [comment]
Do you happen to know what dataset this occurred with?  I seem to recall this message popping up on NcSOS on certain datasets where it couldn't find the feature type.

**Comment by kknee** [comment]
@benjwadams - looks like that's the case according to Luke's original post.  At issue here is how that error is displayed to the user in the catalog, not fixing the fact that harvesting errors when the feature type is null.

**Comment by benjwadams** [comment]
Here's an example dataset where this happened during a harvest on my development instance.  I had seen this message before on NcSOS and it seems to be a provider/NcSOS issue, so my suspicion is correct.

http://data.ioos.us/gliders//thredds/sos/deployments/rutgers/ru25d-20140104T1705/ru25d-20140104T1705.nc3.nc?service=SOS&version=1.0.0&request=GetCapabilities

**Comment by benjwadams** [comment]
Thanks @daf for your sleuthing.  There's no extra logic to add the deployments harvesting, aside from fetching the records from NGDC GeoPortal for the proper `sys.siteuuid`  (and data type I presume, although I haven't checked yet)  A query against the NGDC GeoPortal shows that it appears to contain the erroneous URL.

    curl -X POST -d '<?xml version="1.0" encoding="utf-8" standalone="no"?><csw:GetRecords xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ogc="http://www.opengis.net/ogc" outputSchema="http://www.opengis.net/cat/csw/2.0.2" outputFormat="application/xml" version="2.0.2" service="CSW" resultType="results" maxRecords="999999" xsi:schemaLocation="http://www.opengis.net/cat/csw/2.0.2 http://schemas.opengis.net/csw/2.0.2/CSW-discovery.xsd"><csw:Query typeNames="csw:Record"><csw:ElementSetName>full</csw:ElementSetName><csw:Constraint version="1.1.0"><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>Title</ogc:PropertyName><ogc:Literal>ru25d-20140104T1705</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter></csw:Constraint></csw:Query></csw:GetRecords>' http://www.ngdc.noaa.gov/geoportal/csw

**Comment by lukecampbell** [comment]
This is an internal issue to gliderdac. I'm dealing with it now.

**Comment by lukecampbell** [comment]
GliderDAC is back and functional.

**Comment by lukecampbell** [comment]
Ugh, ok I dug way deeper. This is a THREDDS issue. GliderDAC generates the metadata that NGDC uses through the NcISO. NcISO is reporting that the sos endpoint is an endpoint that doesn't exist. I need to figure out how to fix this.

**Comment by lukecampbell** [comment]
Example
http://data.ioos.us/gliders//thredds/iso/deployments/rutgers/ru24-20140104T1300/ru24-20140104T1300.nc3.nc?catalog=http%3A%2F%2Fdata.ioos.us%2Fthredds%2Fcatalog%2Fdeployments%2Frutgers%2Fru24-20140104T1300%2Fcatalog.html&dataset=deployments%2Frutgers%2Fru24-20140104T1300%2Fru24-20140104T1300.nc3.nc

**Comment by lukecampbell** [comment]
Ok, the real crux of the issue is this:
![screen shot 2015-03-11 at 10 49 50 am](https://cloud.githubusercontent.com/assets/1155163/6598787/676c25b8-c7dc-11e4-887b-97d24199f4d1.png)

I think one of those is from an old WAF when we were transitioning from 1.0 to 2.0 and it's using an invalid URL.

**Comment by lukecampbell** [comment]
Ok GliderDAC has duplicate ISO Records for the same thredds instance, and one of each duplicate is pointing to the wrong SOS endpoint. I'll need to dig deeper.

**Comment by lukecampbell** [comment]
Still investigating. While the investigation is underway, I'm also adding the logic that will attempt at a better error message.
