### ISSUE TITLE
Service Monitor Sync Bug

### ISSUE THREAD

**Issue by lukecampbell** [ioos/catalog#22]
For example, GCOOS has a large inconsistency between the SOS services published in CKAN and the services shown in CKAN.

https://monitor.ioos.us/services/filter/GCOOS/SOS
https://data.ioos.us/organization/81073df6-f052-491a-b68e-ea76f6591389?res_format=SOS

**Comment by lukecampbell** [comment]
@mwengren I have an update on this. It looks like it's working fine. The problem is that all the registered SOS services all are the same service... 

Uniqueness for an "SOS" Service in the service-monitor is data-provider and URL. Otherwise we'd ping and monitor the same URL for every duplicate record created by the providers.

Will provide more details shortly...

**Comment by lukecampbell** [comment]
![screen shot 2017-01-24 at 4 02 47 pm](https://cloud.githubusercontent.com/assets/1155163/22266622/b55634e2-e24e-11e6-9b07-ad42ed320289.png)

![screen shot 2017-01-24 at 4 03 44 pm](https://cloud.githubusercontent.com/assets/1155163/22266626/b8f7252a-e24e-11e6-845d-9384447a95ec.png)

**Comment by lukecampbell** [comment]
I can probably refactor the service monitor with a new definition of uniqueness, but we should probably discuss.

**Comment by mwengren** [comment]
Ok, let's put a meeting on the calendar to discuss Service Monitor in more detail in the next week or two.   I may need some time to review and assess what the needs are first.

**Comment by lukecampbell** [comment]
I'm surprised there wasn't more in this github issue, we discussed this a lot.

In any case good news!

**Comment by mwengren** [comment]
The inventory is looking better in monitor.ioos.us.   

Looks like the only 'issue' that remains may be the harvesting status.  I'm not sure whether the RA services are down as much as shown, but are the harvesters working properly?

https://monitor.ioos.us/services/filter/NANOOS/SOS
https://monitor.ioos.us/services/filter/GCOOS/SOS

GCOOS appeared down anyway.   NANOOS looked OK.

**Comment by lukecampbell** [comment]
The rest of the issues are tracked by https://github.com/ioos/catalog-ckan/issues/153
