### ISSUE TITLE
Gathering ISO metadata from Hyrax servers

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/catalog#23]
Two ways to gather ISO metadata from Hyrax:

**Method 1:** 

Every directory on Hyrax has a thredds catalog view. 

For every directory view, for example:
http://opendap.jpl.nasa.gov/opendap/OceanTemperature/aquarius/L4/IPRC/v4/7day/2015/001/contents.html

there is a THREDDS catalog.   Just replace "contents.html" with "catalog.xml", like this:

http://opendap.jpl.nasa.gov/opendap/OceanTemperature/aquarius/L4/IPRC/v4/7day/2015/001/catalog.xml

then point your ncISO standalone at that thredds catalog. 

**Method 2:** 

Just replace the ".html" extension on the DAP dataset access form with ".iso".

So instead of 

http://opendap.jpl.nasa.gov/opendap/OceanTemperature/aquarius/L4/IPRC/v4/7day/2015/001/SSS_OI_7D_20150012015007_V40.nc.html

request

http://opendap.jpl.nasa.gov/opendap/OceanTemperature/aquarius/L4/IPRC/v4/7day/2015/001/SSS_OI_7D_20150012015007_V40.nc.iso

**Comment by mwengren** [comment]
@rsignell-usgs Are there any data providers using Hyrax that would be adding datasets to the IOOS Catalog?  If not, we'll close this one as it's rather old and not a big priority to implement otherwise.

**Comment by mwengren** [comment]
Closing issue as no longer needed.
