### ISSUE TITLE
Enable time support for glider data

### ISSUE THREAD

**Issue by BeckyBaltes** [ioos/catalog#232]
Is there a way to query glider data for "currently deployed" gliders.  We want to be able to look at the map and see what is out there right now.

**Comment by carmelortiz** [comment]
Note that this applies to all Catalog maps. Make this a generic time-filtering feature.

**Comment by lukecampbell** [comment]
@benjwadams so, what I was thinking was using bootstrap-date-picker and selecting a start and end date. Then we could use the JSON interface to glider dac (that I'm currently implementing) to list only the dataset ids and catalog points between a start date and end date. 

The other option is to include start and end times when we "reindex_services" for the glider dac entries.

**Comment by kknee** [comment]
@lukecampbell - just remember that we want to keep the solution as general as possible so that it's applicable to the other data categories on the catalog map.

**Comment by kknee** [comment]
this is part of a more general filtering solution, closing in favor of #19
