### ISSUE TITLE
Update sensorml2iso to v1.0.1

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog#25]
Update sensorml2iso release tag to v1.0.1 in code used to generate the NDBC and CO-OPS SOS WAFs.

https://github.com/ioos/sensorml2iso/releases/tag/v1.0.1

**Comment by mwengren** [comment]
@lukecampbell Now that sensorml2iso has a new release, can you update the process that generates the NDBC and CO-OPS WAFs?

**Comment by lukecampbell** [comment]
It should be updated. https://data.ioos.us/stations/waf/

**Comment by lukecampbell** [comment]
It's actually on version 1.0.2
