### ISSUE TITLE
CSW Records missing services

### ISSUE THREAD

**Issue by lukecampbell** [ioos/catalog#26]
> I ran this notebook
> https://gist.github.com/anonymous/6a087c3511b145a490e7bea8bc461876
> and the site is working, but service URLs seem to be missing for some datasets that should have them.
> 
> See cell [12] for example.

@rsignell-usgs

**Comment by lukecampbell** [comment]
@rsignell-usgs for the dataset in the Notebook with the title "CBOFS2 (2014-2015)" https://registry.ioos.us/waf/COMT/cb_hypoxia1415.noaacsdl_roms.ncml.xml

**Comment by lukecampbell** [comment]
This ISO record doesn't have any links or "resources" associated with it, including the DAP URL. I'm going to look into the rest too.

**Comment by lukecampbell** [comment]
The dataset titled "ROMS_RCA" which lies https://registry.ioos.us/waf/COMT/cb_hypoxia.roms_rca.ncml.xml also doesn't have resources. So I'm starting to think this is on the provider's side, I'll keep looking though.

**Comment by lukecampbell** [comment]
Here's the original http://comt.sura.org/WAF/cb_hypoxia.roms_rca.ncml.xml

**Comment by lukecampbell** [comment]
@mwengren could you reach out the COMT folks and see if we can get the OPeNDAP links thrown in these records?

**Comment by lukecampbell** [comment]
@brianmckenna Heads up

**Comment by rsignell-usgs** [comment]
Hmm, interesting.  Other records do include OPeNDAP endpoints:
http://comt.sura.org/WAF/inundation_extratropical.VIMS_SELFE.2005_2D_final_run_without_waves.xml

**Comment by brianmckenna** [comment]
@rsignell-usgs updated WAF with fully qualified dataset IDs. Re-harvested, looks like services are showing on IOOS registry.

**Comment by mwengren** [comment]
@rsignell-usgs Can you confirm this is fixed?

**Comment by rsignell-usgs** [comment]
Before:
![2017-02-22_13-06-18](https://cloud.githubusercontent.com/assets/1872600/23225496/1879de26-f900-11e6-88dd-06ed8241970f.png)

After:
![2017-02-22_13-08-38](https://cloud.githubusercontent.com/assets/1872600/23225501/1dc16796-f900-11e6-969f-473b530ffeca.png)

:champagne:

**Comment by rsignell-usgs** [comment]
Nice work Gang!
