### ISSUE TITLE
Proper handling for ERDDAP

### ISSUE THREAD

**Issue by lukecampbell** [ioos/catalog#277]
A lot of the services we harvest from ERDDAP endpoints are OPeNDAP Sequence (aka TableDAP) endpoints. The standard clients that we're using are not the right tool to harvest these endpoints. We need to adjust our toolset to harvest from sequence dap as well. 

I had no luck with PyDAP on OOI, so I wrote my own, I may be able to re-use some of that code.

**Comment by carmelortiz** [comment]
This issue didn't seem to fit well in any other milestone, and seemed like we want to address it sooner than later, so I added it to milestone 3.2.2. The other choice is to put it in 4.0, I think it mostly depends on the level of effort required.

**Comment by kknee** [comment]
@lukecampbell can you comment on level of effort?  I think we've got a workaround in place for now, so if the effort to resolve correctly is high, we should move out of this milestone.

**Comment by dpsnowden** [comment]
See https://github.com/OSGeo/Cat-Interop for a list of desirable gmd:protocol elements that identify ERDDAP services as ERDDAP:tabledap or something similar.  All ERDDAP services deployed in the last couple months should have ISO records that correctly distinguish ERDDAP DAP servers from other DAP servers.  I think this is a solved problem but we may need to encourage data providers to upgrade to recent versions of ERDDAP.

**Comment by lukecampbell** [comment]
I think this is either all set or very close to all set. We already deal with ERDDAP by looking at the JSON responses. And, the latest version of ERDDAP publish ISO metadata records that clearly indicate itself as ERDDAP. 

I will follow up with this when we get to testing the harvesting changes to make sure that this is taken care of.

**Comment by benjwadams** [comment]
So in summation we ought to begin the transition to recognizing the proper ERDDAP <gmd:protocol> elements while leaving in place the url string search hack to accomodate older versions, correct?

**Comment by lukecampbell** [comment]
This is no longer an observable issue.
