### ISSUE TITLE
CO-OPS not found in example CSW notebook

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/catalog#29]
We have this CSW search example notebook in the IOOS Demos Gallery:
https://github.com/ioos/notebooks_demos/blob/master/notebooks/2016-12-19-exploring_csw.ipynb

I just tried running it, and it fails in cell [8] because it can't find any records with "CO-OPS". 

I thought it might be a stop time issue, since the notebook only looks for the last 7 days, but the records it should be finding seem okay:
https://data.ioos.us/dataset/urn-ioos-station-noaa-nos-co-ops-9439040-station-astoria-or
https://registry.ioos.us/waf/NOAA%20CO-OPS/opendap.co-ops.nos.noaa.gov-urn_ioos_station_NOAA.NOS.CO-OPS_9439040.xml

@lukecampbell , is there some CSW sync problem at play here?

**Comment by lukecampbell** [comment]
@benjwadams is troubleshooting the CO-OPS duplication issue right now so there's a chance that it's being rebuilt right now.

**Comment by rsignell-usgs** [comment]
And I'm happy to report I just tried running the notebook again and it worked fine.  
So thanks @benjwadams !
