### ISSUE TITLE
Consider using Cube for data storage

### ISSUE THREAD

**Issue by daf** [ioos/catalog#29]
[Cube](http://square.github.io/cube/) is a full featured piece of software using our existing tech stack (mongodb) to store time-series event.

We currently do it ourselves for service monitoring, and we'll need to add some additional time-series stuff for observation number collection - consider a switch to a more standardized approach.

**Comment by lukecampbell** [comment]
This is OBE by the harvesting metrics we're now doing, and our migration to PostGIS in the near future.
