### ISSUE TITLE
Allow for non-interactive re-harvest

### ISSUE THREAD

**Issue by kwilcox** [ioos/catalog#30]
It would be very useful if I could kick off a re-harvest of a Data Source without having to manually login to https://registry.ioos.us. My use case would be to kick off a re-harvest every time we regenerate our WAF based ISO records.

Even better would be a way for me to tell whatever system the registry is feeding that a single record was updated in the WAF. This would avoid the registry having to re-harvest an entire collection when only a few records have changed.

**Comment by lukecampbell** [comment]
I like the idea. Just a comment, authentication will still be required even if we exposed an API.

**Comment by kwilcox** [comment]
An API key on the user account to be included with the request would be :ok_hand:.

**Comment by lukecampbell** [comment]
Yeah I think we can make that happen.

**Comment by mwengren** [comment]
@lukecampbell what's the LOE for this?

**Comment by lukecampbell** [comment]
A few days, meteor has the mechanisms to make this happen, we just need to hook it up.

**Comment by lukecampbell** [comment]
https://github.com/ioos/catalog-harvest-registry/pull/99

I added it, now all that's left is to document it.
