### ISSUE TITLE
Better job monitoring

### ISSUE THREAD

**Issue by daf** [ioos/catalog#30]
Our job queueing system (rq) does not keep its results around indefinitely (it does for errors, but not successes).  It also is very difficult to track when things happen aside from live-monitoring log files which limits forensic analysis of issues.

Would be great to have better tracking of metrics of the jobs - when certain jobs ran, how long they took, their frequency - will help us better track down issues (why wasn't this harvested, didn't grab new services from NGDC) etc.

Could use Cube for this also (see #29)

**Comment by lukecampbell** [comment]
This was done with the harvesting statistics.
