### ISSUE TITLE
Problems with harvesting SOS services 

### ISSUE THREAD

**Issue by abirger** [ioos/catalog#318]
The Catalog Inventory demonstrates that SOS harvesting is crippled: while harvesting of some providers is consistently successful, the others fail harvesting time and again. The latter group includes but is not limited to, AOOS, CeNCOOS and NDBC. 

Some efforts have been made earlier to identify the source of the problem ([issue #173](https://github.com/ioos/catalog/issues/173)); however, it seems that the ticket was closed before it gets to the bottom of it. For example, AOOS and CeNCOOS timed out consistently, and it is not clear why exactly it happens (no problem manually with browser). 

We need a clear-cut distinction between the failures due to the Catalog harvesting mechanism deficiencies, and the ones due to the registry/provider's issues.

**Comment by benjwadams** [comment]
Interesting, looked at AOOS and it now appears that it's the RQ worker timing out:

    {       "date" : ISODate("2015-02-10T08:43:18.471Z"),   "successful" : false,   "message" : "Traceback (most recent call last):
      File \"/home/monitoring/ioos-service-monitor/ioos_catalog/models/harvests.py\", line 95, in harvest
        message = SosHarvest(service).harvest()
      File \"/home/monitoring/ioos-service-monitor/ioos_catalog/tasks/harvest.py\", line 235, in harvest
        self.process_station(proc)
      File \"/home/monitoring/ioos-service-monitor/ioos_catalog/tasks/harvest.py\", line 253, in process_station
        metadata_value = etree.fromstring(self._describe_sensor(uid))
      File \"/home/monitoring/ioos-service-monitor/ioos_catalog/tasks/harvest.py\", line 196, in _describe_sensor
        return self.sos.describe_sensor(**kwargs)
      File \"/home/monitoring/.virtualenvs/monitoring/lib/python2.7/site-packages/OWSLib-0.8.10-py2.7.egg/owslib/swe/observation/sos100.py\", line 131, in describe_sensor
        response = openURL(base_url, data, method, username=self.username, password=self.password, **url_kwargs).read()
      File \"/opt/python-2.7.5/lib/python2.7/socket.py\", line 351, in read
        data = self._sock.recv(rbufsize)
      File \"/opt/python-2.7.5/lib/python2.7/httplib.py\", line 543, in read
        return self._read_chunked(amt)
      File \"/opt/python-2.7.5/lib/python2.7/httplib.py\", line 585, in _read_chunked
        line = self.fp.readline(_MAXLINE + 1)
      File \"/opt/python-2.7.5/lib/python2.7/socket.py\", line 476, in readline
        data = self._sock.recv(self._rbufsize)
      File \"/home/monitoring/.virtualenvs/monitoring/lib/python2.7/site-packages/rq/timeouts.py\", line 36, in handle_death_penalty
        'value (%d seconds).' % self._timeout)
    JobTimeoutException: Job exceeded maximum timeout value (180 seconds).
    " }

As there are quite a few stations in the AOOS GetCapabilities I'm not entirely surprised it's taking over 180 seconds.

**Comment by benjwadams** [comment]
This issue is far too broad in scope.  Due to this, I'm closing the issue for the time being, but we can certainly reference the spreadsheet and other assets.  I've split the AOOS/CeNCOOS and COOPS/NDBC issues into #359 and #360 respectively, since they address different concerns.  Discussion and fixes for those particular issues should continue therein.  If it's desired to address some of the other issues mentioned by @abirger, please create a separate, specific issue.

**Comment by carmelortiz** [comment]
Validated fixes under issues #359 and #360.
