### ISSUE TITLE
Problem with Unidata WaveWatch III East Coast

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/catalog#32]
@lukecampbell was demonstrating the [catalog harvester interface](https://registry.ioos.us) at the DMAC meeting and randomly picked the Unidata WAF, reharvested the ISO records and found that one dataset had a problem.   Since this is a unidata dataset, I'm bringing in @lesserwhirls here also.  

Luke then showed how you could sort datasets by error to locate the problem, and then drilled down to this screen to show the error:
![2017-03-18_9-00-23](https://cloud.githubusercontent.com/assets/1872600/24072183/6668f6dc-0bb9-11e7-85c6-3fc31bfdf722.png)

It turns out that the minimum latitude 
http://thredds.ucar.edu/thredds/dodsC/grib/NCEP/WW3/Regional_US_East_Coast/Best.ascii?lat[330]
for this particular model is not quite 0, but is -1.6391277E-6.  

So that value with the Exponential notation gets written into the THREDDS [ISO record]( 
http://thredds.ucar.edu/thredds/iso/grib/NCEP/WW3/Regional_US_East_Coast/Best?catalog=http%3A%2F%2Fthredds.ucar.edu%2Fthredds%2Fcatalog%2Fgrib%2FNCEP%2FWW3%2FRegional_US_East_Coast%2Fcatalog.html&dataset=grib%2FNCEP%2FWW3%2FRegional_US_East_Coast%2FBest)
in places like:
```
<gmd:southBoundLatitude>
<gco:Decimal>-1.6391277313232422E-6</gco:Decimal>
</gmd:southBoundLatitude>
```
and that is causing the error for some reason. 

So @lukecampbell or @mwengren, is this a CKAN problem (e.g. it should be able to read exponential notation in an ISO file) or an NcISO problem (e.g. the exponential notation is not allowed in ISO)?

In either case, when we fix the problem for this one pesky East Coast WW III dataset, we will fix a generic issue for the community!   

A great example of how using the catalog improves interoperability!

**Comment by lukecampbell** [comment]
The XML Schema Definition doesn't allow exponential notation:

http://www.datypic.com/sc/niem21/e-gco_Decimal.html
Which links to:
http://www.datypic.com/sc/xsd/t-xsd_decimal.html

**Comment by lukecampbell** [comment]
I looked into it a little more, I think that we'd need to patch thredds-iso so that it doesn't print floating point values in exponential notation.

**Comment by rsignell-usgs** [comment]
@geoneubie to the rescue?

**Comment by rsignell-usgs** [comment]
Closing in favor of https://github.com/Unidata/thredds/issues/783

**Comment by geoneubie** [comment]
@rsignell-usgs I see this has been closed, what was the resolution?

**Comment by rsignell-usgs** [comment]
@geoneubie, I moved the issue here, remember?
https://github.com/Unidata/thredds/issues/783
