### ISSUE TITLE
Add link to the main IOOS website from the landing page

### ISSUE THREAD

**Issue by carmelortiz** [ioos/catalog#327]
From IOOS Catalog Feedback form:

"I think a good addition could be some sort of stakeholder story per region with a picture of the stakeholder and a small testimony."

I think this information exists on ioos.noaa.gov and shouldn't really be part of the Catalog. But perhaps we need a prominent link back to the main IOOS website from the landing page to reinforce the fact that the Catalog is a very specific tool and not the IOOS website.

**Comment by benjwadams** [comment]
@kknee, Couple questions on 1)  
  a) There are two "U.S. IOOS"/"IOOS" in the welcome paragraph.  Should they both be hyperlinked?
  b) Pursuant to #325, #344 has expanded the abbreviation,  Should this also be hyperlinked?

**Comment by carmelortiz** [comment]
I think it's sufficient to only hyperlink the first "US IOOS" in the welcome paragraph, particularly if we have an IOOS URL down at the bottom of the page.

My only other thought on this was to have the "IOOS" logo in the top (light gray) navigation bar link back to ioos.nooa.gov. I'm guessing you can't make it have different behavior from the Catalog landing page than from all other Catalog pages. In that case, the hyperlink from the welcome paragraph and link at the bottom of this page would suffice.

**Comment by kknee** [comment]
@benjwadams just to be clear - let's hyperlink the expanded abbreviation.

**Comment by benjwadams** [comment]
Welcome text:

![link_text](https://cloud.githubusercontent.com/assets/4118886/5963060/d8279f1c-a7b6-11e4-9400-18f15e6c84f0.png)

Link above contact:

![web_link](https://cloud.githubusercontent.com/assets/4118886/5963065/ddfd9766-a7b6-11e4-8b3b-6355c9aba261.png)

Give any feedback

**Comment by lukecampbell** [comment]
We'll probably want some icons or images instead of plain old text.

**Comment by carmelortiz** [comment]
Validated fix.
