### ISSUE TITLE
Add details about harvest success rate to each service page

### ISSUE THREAD

**Issue by kknee** [ioos/catalog#328]
so that the distribution of successes and failures over time is more apparent.

This can be text based for now, consider a plot in the future.

**Comment by benjwadams** [comment]
Just for notes:
>
> We need a table view that displays the last 30 or so harvest attempts and messages
>

**Comment by benjwadams** [comment]
The harvest attempts seem already limited to the past 20 results, don't see anything > 20 harvest results.  Have limited to 30 anyhow in the code.

**Comment by lukecampbell** [comment]
![screen shot 2015-03-11 at 10 25 03 am](https://cloud.githubusercontent.com/assets/1155163/6598316/37986c5a-c7d9-11e4-87d1-895bf06c189c.png)

**Comment by carmelortiz** [comment]
Validated. Note, this has become a great feature/tool for use in monitoring service uptime across the enterprise.
