### ISSUE TITLE
Clean up dead SCCOOS links

### ISSUE THREAD

**Issue by carmelortiz** [ioos/catalog#335]
Catalog Inventory: This is the old catalog which provides some filters. Similar functionality to the Explore dropdown in the top menu. Looks like they have some dead SCCOOS links in there.  We’ll have to follow up on that.

**Comment by benjwadams** [comment]
http://catalog.ioos.us/services/filter/SCCOOS  shows that all current services are active and have been recently harvested.  Has this issue been taken care of?

![scoos_inventory_2015_01_21](https://cloud.githubusercontent.com/assets/4118886/5844686/f11391e0-a183-11e4-9c1f-bcaa1e84fbf7.png)

**Comment by kknee** [comment]
Looks like SCCOOS has updated to RC8 and harvests are successful.  Closing.
