### ISSUE TITLE
Begin recording metrics to view changes over time

### ISSUE THREAD

**Issue by dpsnowden** [ioos/catalog#340]
The metrics and reports we are generating as part of the project need to be saved periodically so we can see changes over time.  There are a few issues that have been closed that described this requirement but I don't think we are actually doing this.  Need to revisit this requirement and dig up some of the older issues for clarification.

**Comment by kknee** [comment]
@dpsnowden @carmelortiz - what's the requirement for ASA on this one?  Are their opportunities for automating this that should be explored or is @carmelortiz going to do this manually?

**Comment by carmelortiz** [comment]
This can eventually support a more dynamic IOOS By The Numbers. At a minimum, we should track and be able to report on 1) # datasets and 2) # services. I'll go through old requirements and suggest other metrics that would be valuable. 

In the short term, the data may just be a .csv file that can be retrieved. Eventually we would want a landing page or easier GUI access to the data.

**Comment by benjwadams** [comment]
My thought is to take a snapshot with every harvest cycle, and tack on a timestamp.  From there, we can get the count of the services/datasets for that particular instant in time, and store these in the database separately.  In this way we can visualize how services/datasets grow over harvest cycles.

**Comment by dpsnowden** [comment]
Sounds good @benjwadams.

On Tue, Jan 20, 2015 at 3:33 PM, benjwadams <notifications@github.com>
wrote:

> My thought is to take a snapshot with every harvest cycle, and tack on a
> timestamp. From there, we can get the count of the services/datasets for
> that particular instant in time, and store these in the database
> separately. In this way we can visualize how services/datasets grow over
> harvest cycles.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ioos/catalog/issues/340#issuecomment-70727576>.
>



-- 
Derrick Snowden
Chief, Operations and Communications Division
NOAA/NOS/US Integrated Ocean Observing System Program
<http://www.ioos.noaa.gov>
1100 Wayne Ave, Suite 1225
Silver Spring, MD 20912
+1 301 427 2464 (o), +1 301 427 2073 (f)
Facebook <http://www.facebook.com/usioosgov> | Twitter
<https://twitter.com/usioosgov>

**Comment by benjwadams** [comment]
@carmelortiz 
> At a minimum, we should track and be able to report on 1) # datasets and 2) # services.

I'd imagine these would be active, recently harvested services, correct?

**Comment by benjwadams** [comment]
> - Total Services
> - Services by type (DAP, WCS, WMS)
> - Total Datasets
> - Total Services for each RA
> - Total Datasets for each RA

**Comment by carmelortiz** [comment]
@benjwadams "active, recently harvested services" are great, but if we're storing the data anyway it would be interesting to have some visibility in to services that had previously been active/harvested but have been offline or unresponsive for some time.

**Comment by carmelortiz** [comment]
Some additional metrics that were previously discussed in #137:
- # platforms
- TB's of data

**Comment by lukecampbell** [comment]
![screen shot 2015-03-11 at 10 25 03 am](https://cloud.githubusercontent.com/assets/1155163/6598282/f94805dc-c7d8-11e4-959f-072354957c7e.png)

**Comment by lukecampbell** [comment]
We are now collecting the metrics but we don't have a way to present the data or generate reports yet. Might be nice to have in 3.3
