### ISSUE TITLE
Remove Glider_DAC_2 from Catalog Map

### ISSUE THREAD

**Issue by kknee** [ioos/catalog#342]
No longer necessary as DAC2.0 and 1.0 share the same UUID and both are represented in the Glider_DAC category.

**Comment by benjwadams** [comment]
> No longer necessary as DAC2.0 and 1.0 share the same UUID

Just to clarify, is this the same UUID in GeoPortal?

**Comment by benjwadams** [comment]
OK, so going to change any data providers with "Glider_DAC_2" to "Glider_DAC" and remove any references where necessary.

**Comment by kknee** [comment]
I don't think you even need to do that.  Glider_dac_2 points to a Rutgers dev server, @lukecampbell can confirm, but I think it can simply be removed.

**Comment by lukecampbell** [comment]
Just remove it.

Glider DAC 2 and 1 are already being ingested by NGDC under the existing UUID

**Comment by carmelortiz** [comment]
Validated.
