### ISSUE TITLE
Make the end of the trajectory clear when plotting glider trajectories on the map.

### ISSUE THREAD

**Issue by dpsnowden** [ioos/catalog#346]

**Comment by daf** [comment]
https://github.com/bmschmidt/D3-trail :smile:

**Comment by lukecampbell** [comment]
![screen shot 2015-01-22 at 3 08 45 pm](https://cloud.githubusercontent.com/assets/1155163/5863589/9e1a49dc-a248-11e4-9ddf-8ceeacaf3194.png)

This currently exists in some places. I know there were some comments about the glider symbol but the idea, I believe, is consistent.

**Comment by benjwadams** [comment]
^Where's this from?

**Comment by dpsnowden** [comment]
Can see a demo of the 3.3 features before launch? 





        




On Fri, May 1, 2015 at 8:50 AM -0700, "Luke Campbell" <notifications@github.com> wrote:












Closed #346.
