### ISSUE TITLE
Investigate issues with reported asset type for Gliders

### ISSUE THREAD

**Issue by kknee** [ioos/catalog#353]
This may simply require more instructions to GliderDAC data providers but also merits a quick investigation of whether Paegan is the culprit.

![image](https://cloud.githubusercontent.com/assets/196868/5968617/acf7bc9c-a7e7-11e4-99b5-8e132ab2b3eb.png)

**Comment by lukecampbell** [comment]
I looked into this, Paegan is almost certainly the culprit here.

**Comment by benjwadams** [comment]
Actually, it's some code I wrote that takes preference for CGRID.
https://github.com/ioos/catalog/blob/master/ioos_catalog/tasks/harvest.py#L659-L660
I don't remember the exact reasoning, but I think Paegan was OK at picking up curvilinear grids, so I opted to use them.  I hadn't expected glider tracks to be picked up as curvilinear grids.

It might also be partially related to a Paegan version mismatch.  I don't see the versioning info in the Python module, but my dev workspace shows the Paegan datatype as NCell, whereas in production it appears to be reporting CGrid.

**Comment by benjwadams** [comment]
In short, upgrading the Paegan version to the newest may fix the issue.

**Comment by benjwadams** [comment]
I can't open a lot of the spray gliders on production.  Harvest keeps not returning a valid response, despite saying it's successful on harvests status.

    -> cd = CommonDataset.open(self.service.get('url'))
    (Pdb) n
    syntax error
    context: <htm^><head><title>301 Moved Permanently</title></head><body bgcolor="white"><center><h1>301 Moved Permanently</h1></center><hr><center>nginx/1.4.7</center></body></html>
    ValueError: ValueErr...tasets',)

**Comment by benjwadams** [comment]
Above turned out to be due to an outdated C library.  I'm going to just remove the CGRID precedence, not sure why I added that particular snippet.
