### ISSUE TITLE
Add filtering by time frame to asset map

### ISSUE THREAD

**Issue by benjwadams** [ioos/catalog#384]
From #19.  Add filtering by timestamp to asset map.

**Comment by lukecampbell** [comment]
@benjwadams what's the status on this?

**Comment by benjwadams** [comment]
Time filter has been added on the frontend.  I am working on adding the necessary backend components so that start and end times are properly picked up for DAP and SOS.

**Comment by benjwadams** [comment]
Can we please close this?  I think the PR implements the basic functionality desired.
