### ISSUE TITLE
SOS services filter returns 404 error

### ISSUE THREAD

**Issue by carmelortiz** [ioos/catalog#389]
From the Catalog Inventory landing page, clicking on the SOS button (effectively filtering on SOS services) yields a 404 error.

**Comment by lukecampbell** [comment]
@carmelortiz could you try again and reverify? We may have fixed this in the process of making changes for 3.4.

**Comment by carmelortiz** [comment]
Yep, just re-tested and it works. Pretty snappy, too, considering the number of rows returned in the table.

**Comment by lukecampbell** [comment]
I've got some big changes in the works that'll make catalog lightning fast. Right now everyone that views catalog are competing for the server's time to process their request, format HTML etc. The changes I've got in store will cause pages to load IMMEDIATELY and as the information comes from the server it will expand the page. By the time you can even get your mouse to the scroll bar the page will have completely loaded and it won't place that much of load on the server.
