### ISSUE TITLE
Add a facet in the CKAN interface to identify the Data Provider within an Organization

### ISSUE THREAD

**Issue by dpsnowden** [ioos/catalog#41]
There is a need to identify and search for Data Providers within an RA (or other) organization structure.  We should be able to harvest a data provider and their association to an Organization.  What would it take to add a "Data Provider" menu in the image below.

![image](https://cloud.githubusercontent.com/assets/3603125/25100157/0a2aff56-237d-11e7-9ff1-45b1b5a34048.png)

**Comment by lukecampbell** [comment]
Adding it to the UI would be trivial. Finding a consistent pattern in which the metadata identify and label data providers would be non-trivial. This falls under the category of "attribution" problems.

**Comment by mwengren** [comment]
This is related to ioos/catalog-ckan#145, or rather #145 is a precursor for making this work within the UI, at least for SOS stations with metadata from sensorml2iso.  This fix should add a second entry under the 'Access' tab for these datasets (and then hopefully enabling facet filtering from there is not difficult as you say).  

@lukecampbell @benjwadams  can one of you look at resolving #145?  

From ioos/catalog-ckan#145, the sensorml2iso module has already been enhanced to include an 'originator' block of metadata that corresponds to the 'operator' term in the IOOS SOS SensorML specification ('originator' seemed the best mapping from 'operator' in the ISO codelist values for CI_RoleCode I could find).  

Here's an example for a PacIOOS station served by NDBC: 

Catalog dataset link: https://data.ioos.us/dataset/barbers-point-hi-2-1651 

and corresponding XML in Registry:

https://registry.ioos.us/waf/NOAA%20NDBC/a7b4eff56989d417b2fb606ecd3f4c4ebb19ecc1.xml.  Look for PacIOOS block with 'originator' RoleCode value.  

cc @emiliom

**Comment by emiliom** [comment]
Thanks, @dpsnowden and @mwengren. Yeah, for SOS, this would be pulled from the SensorML `operator` classifier, which is part of the IOOS-defined set of SensorML conventions/vocabularies:
- https://github.com/ioos/vocabularies#organization-descriptors-and-roles
- http://mmisw.org/ont/ioos/definition/operator

Off the top of my head, I don't know if there's a good equivalent in CF/ACDD that's used reasonably consistently. But it's worth exploring.

**Comment by lukecampbell** [comment]
ncISO maps the following to the `CI_Responsible_Party` with the role code `originator`

`creator_name` -> `individual-name`
`creator_email` -> `contact-info/email`
`institution` -> `organisation-name`
`creator_url` -> contact-info/online-resource`

https://github.com/Unidata/threddsIso/blob/master/src/main/resources/xsl/nciso/UnidataDD2MI.xsl#L384-L391

**Comment by benjwadams** [comment]
We would probably need an authoritative list of institution names and their synonyms, i.e. UCSD would map to UC San Diego and University of California San Diego.  NCEI, for example, has had issues with arbitrary institution names being specified for glider data.

**Comment by mwengren** [comment]
@benjwadams Let's enable this capability by adding a faceted filtering capability on the 'Originator' CKAN extra field (from ISO metadata).  Also add an extra menu item on the left called 'Data Provider' or something similar.

**Comment by benjwadams** [comment]
Made some good progress on this (called "Data Provider" "Data Originator" instead, oops, will fix).   I hope to have something for a PR tomorrow.

![data_originator_search](https://user-images.githubusercontent.com/4118886/54650298-382b2180-4a84-11e9-9575-ce3908052845.png)
![data_originator_filter_list](https://user-images.githubusercontent.com/4118886/54650326-54c75980-4a84-11e9-8f80-f6e72350bc75.png)

**Comment by mwengren** [comment]
@benjwadams  Great!  Let's just call it 'Data Provider' like you mentioned, that seems to be the colloquial term in use.   Let me know if you deploy that on the catalog-dev site and I'll take a look.

**Comment by benjwadams** [comment]
This has been implemented by https://github.com/ioos/catalog-ckan/pull/201.  Closing.
