### ISSUE TITLE
Strange datasets when searching for "unidata"

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/catalog#42]
https://data.ioos.us/dataset?q=unidata

What the heck are these strange datasets at the top of the list?

![2017-04-19_8-52-12](https://cloud.githubusercontent.com/assets/1872600/25180901/b3177598-24dd-11e7-86df-fdd383c386af.jpg)

**Comment by lukecampbell** [comment]
I don't see them

**Comment by lukecampbell** [comment]
![screen shot 2017-04-19 at 9 18 59 am](https://cloud.githubusercontent.com/assets/1155163/25181992/3dccb880-24e1-11e7-8961-9e766817a910.png)

**Comment by lukecampbell** [comment]
I ran a clear duplicates script about 20 minutes ago, maybe those were some bizarre dangling datasets that got cleaned up?

I'm also running the reindex now, it's at 2232/6320 datasets

**Comment by lukecampbell** [comment]
They're back, so they're likely genuine.

**Comment by lukecampbell** [comment]
They're from datasets with no title:
https://registry.ioos.us/waf/Unidata/1d8fa4c443e3b47e5fe1586f55fa675c6091cd6c.xml

**Comment by lukecampbell** [comment]
![screen shot 2017-04-19 at 9 47 53 am](https://cloud.githubusercontent.com/assets/1155163/25183346/513c1600-24e5-11e7-81f8-05b7bbf73f0a.png)

**Comment by rsignell-usgs** [comment]
@lukecampbell , interesting.   I'm giving a demo of the catalog today here at Unidata, and I'll ask use this to demonstrate how using a catalog is a good way to expose issues with the metadata!  (and BTW, can we avoid mucking with the catalog between 4-7pm Eastern today?)

**Comment by lukecampbell** [comment]
Yes, we can certainly do that! If you have demos you want to give in the future, if you let me know I can make sure nothing but normal operations take place during those timeframes. I'll also try to bounce maintenance windows off you too.

**Comment by mwengren** [comment]
@rsignell-usgs I believe this issue is closed/resolved?  Ok to close it?

**Comment by rsignell-usgs** [comment]
Yes, this issue has been resolved, so I'll close, but I can't many of the unidata datasets now.  I'll raise another issue.
