### ISSUE TITLE
Some metadata for NANOOS i52N SOS service is scrambled with a different service

### ISSUE THREAD

**Issue by emiliom** [ioos/catalog#423]
Under the NANOOS services listing, http://catalog.ioos.us/services/filter/NANOOS, the single entry under the "data.nanoos.org" server name is supposed to be a 52North SOS service. I don't know when this happened, but the name and other top-level metadata has gotten conflated with that from another NANOOS service. You'll see on that page that it's listed as a DAP service (it's not), and its name is shown as being identical to another service ("OSU SST Climatology, MODIS Aqua, West US..."). Clicking on the service (http://catalog.ioos.us/services/542ef1f48c0db372dac2fd63), only **Data Access URL** and **Harvested Datasets** are correct (and refer to the SOS service). Everything else is corrupted and is from a different NANOOS service. FYI, the [SOS GetCapabilities endpoint is working just fine](http://data.nanoos.org/52nsos/sos/kvp?service=SOS&request=GetCapabilities&acceptVersions=1.0.0).

Pretty crazy ...

**Comment by emiliom** [comment]
Sorry to bug, but has someone been able to look into this? The NANOOS i52N SOS service is the main, broadest service NANOOS has registered on the catalog, so having its presentation corrupted/misrepresented on the catalog is an important problem to us. @robragsdale, @lukecampbell? Thanks.

**Comment by kknee** [comment]
@emiliom we'll take a look asap.

**Comment by lukecampbell** [comment]
A lot of this stems from the records registered with the NGDC Geoportal
https://www.ngdc.noaa.gov/docucomp/collectionSource/list?recordSetId=2604647&componentId=&serviceType=&serviceStatus=&serviceUrl=&search=List+Collection+Sources

I'm having trouble tracing out how coastwatch wound up on NANOOS though. The IOOS catalog is incapable of assigning a data provider to a source, _for now_, it all comes from geoportal. 

I can disable any sources if we want but it would be good to fix the source, I think, if we can.

**Comment by emiliom** [comment]
Thanks, @kknee and @lukecampbell. NANOOS has a WAF with 4 datasets hosted on Coastwatch ERDDAP; that's been working fine on the Catalog for the last 7 months -- see ioos/registry#51. The SOS service record that's mangled is incorrectly getting some metadata from one of those WAF datasets. Everything had been fine until recently (sometime over the last month, probably), and we haven't changed anything on our end.

I can see how that might be confusing, but as far as I can see there are no issues on the NGDC registry you linked to. There's also nothing obviously wrong with [the NGDC iso metadata for our NANOOS SOS service](http://www.ngdc.noaa.gov/geoportal/rest/document?id={AFCA152E-AB1C-4C5D-94A6-D1ABE62D9387}).

**Comment by emiliom** [comment]
This problem is indeed fixed. Thank! But new ones were created. On the [NANOOS service listing](http://catalog.ioos.us/services/filter/NANOOS), each coastwatch DAP service is now duplicated, and is not harvesting properly. But corresponding WMS services are fine. As a reminder, these are coming from ISO records hosted on a NANOOS WAF but pointing to coastwatch services.

**Comment by lukecampbell** [comment]
I don't think there are duplicates, they have similar titles but they are different datasets, I think.

- OSU Chlorophyll Climatology, MODIS Aqua, West US, July 2002-June 2013 
- OSU SST Climatology, MODIS Aqua, West US, July 2002-June 2013
- OSU SST Anomaly, MODIS Aqua, West US, July 2002-June 2014
- OSU Chlorophyll Anomaly, MODIS Aqua, West US, July 2002-June 2014

As for the harvesting issues, I just reharvested them successfully. If ERDDAP returns any HTTP code besides 200 or a redirect, the service is identified as "Down", I'm not sure why ERDDAP returned something other than a 200, but they're up now.

**Comment by emiliom** [comment]
Thanks, @lukecampbell. Everything is fine now! But there really were duplicates when I reported that problem. Each of the 4 datasets you listed had 2 DAP listings (and 1 WMS listing, as it should be). Now it's all perfect: each of those datasets has 1 DAP + 1 WMS service.

Everything looks good now with all NANOOS services.

**Comment by lukecampbell** [comment]
You could have potentially viewed the page while the service was reindexing to recover from the earlier harvesting errors.
