### ISSUE TITLE
Catalog harvesting stopped Jan 15. Is it being overhauled, or just broken?

### ISSUE THREAD

**Issue by emiliom** [ioos/catalog#440]
As far as I can tell, the last harvest date on the IOOS Catalog is January 15, a month ago. If harvesting is broken due to an overhaul going on, can you let the RA's and others know, either via an email or -- better -- a message on the front  page of the Catalog announcing that work is being done, ETA for completion, etc?

If it's broken and no one had noticed, any idea when it might be fixed?

Otherwise, adding or modifying services and datasets at this time is frustrating, b/c we can't check the complete workflow to the Catalog.

I left a message about this via the Catalog feedback page last week, but didn't get a reply.

**Comment by kknee** [comment]
@emiliom good catch, the workers were running, so we didn't notice any issues, but they lost their connection to the broker and weren't performing their tasks.  We just restarted them and they're back to processing now.  May take a bit of time for all the harvests to complete.

**Comment by emiliom** [comment]
Thanks, @kknee! It looks fixed. I'm glad it was straightforward.

**Comment by abirger** [comment]
@emiliom , @kknee , although the issue is closed for now, I think that there should be some traps for catching the issues like that before users start screaming...

**Comment by emiliom** [comment]
I agree with @abirger. FYI I closed the issue b/c I was the one who created it, and in its current incarnation it was specific to what was going right now, and that immediate problem is fixed.

**Comment by kknee** [comment]
I'll open a new, more general issue.
