### ISSUE TITLE
Please reharvest CeNCOOS datasets

### ISSUE THREAD

**Issue by kwilcox** [ioos/catalog#446]
All of the SOS/DAP station datasets are failing: http://catalog.ioos.us/services/filter/CeNCOOS because they need to be re-harvested at the NGDC level. The URLs changed some months ago but the unique identifiers for each dataset did not.

**Comment by lukecampbell** [comment]
Wouldn't this go to NGDC then?

**Comment by kwilcox** [comment]
Whoops, wrong repo!
