### ISSUE TITLE
Are the unidata datasets being harvested?

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/catalog#45]
It looks like the unidata iso records are still getting updated here:
http://thredds.axiomdatascience.com/iso/unidata/
but it appears that they are not making it into the catalog.  

This search on the "HRRR" model, for example, doesn't turn up anything:

https://data.ioos.us/dataset?q=HRRR

**Comment by mwengren** [comment]
@kwilcox, it looks like http://thredds.axiomalaska.com/iso/unidata/ disappeared.  

Any news on whether this will be restored or if it moved to another URL?

**Comment by kwilcox** [comment]
It's always been http://thredds.axiomdatascience.com/iso/unidata/, must have been registered wrong?

**Comment by mwengren** [comment]
Ok, will update.  We don't have a way to track whether URLs have changed over time in the Registry, but it must have been registered incorrectly as axiomalaska.com originally and that must have changed on your side to not redirect to axiomdatascience.com any more.

**Comment by mwengren** [comment]
Should all be back now: https://data.ioos.us/organization/unidata.  Will close.
