### ISSUE TITLE
Can ncISO output links to THREDDS dataset pages, in addition to the service links?

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog#50]
From the Catalog, it would be nice if one of the links included under 'Data and Resources' links directly to the THREDDS dataset page.  

Here's an example:

[GEBCO_08 Grid](https://data.ioos.us/dataset/gebco_08-grid) -> http://thredds.aoos.org/thredds/catalog.html?dataset=GEBCO

rather than: [GEBCO_08 Grid](https://data.ioos.us/dataset/gebco_08-grid) -> http://thredds.aoos.org/thredds/dodsC/GEBCO.nc.html -> http://thredds.aoos.org/thredds/catalog.html -> manuallly navigate THREDDS catalog tree -> http://thredds.aoos.org/thredds/catalog.html?dataset=GEBCO

This would be an update to [threddsISO](https://github.com/Unidata/threddsIso) to output the dataset page links in the ISO XML.

cc: @kwilcox @geoneubie @rsignell-usgs

**Comment by mwengren** [comment]
cc: @kevin-obrien @noaaroland FYI, just wanted to bring this idea to your attention.  

Would an enhancement request/issue be appropriate on the threddsISO repo?

**Comment by benjwadams** [comment]
Going to close this as I don't really have control over the ISO metadata generated by clients.  It's not usually desirable to be editing metadata, but if it's something we really want to revisit, we can.
