### ISSUE TITLE
API for catalog data access

### ISSUE THREAD

**Issue by daf** [ioos/catalog#50]
JSON?

**Comment by lukecampbell** [comment]
bump :+1: 
I've already started out of necessity but if there's a specific direction for this, we should discuss.

**Comment by rsignell-usgs** [comment]
I tried hitting the csw service at `http://data.ioos.us/csw` with a bounding box filter request like
```
from owslib.csw import CatalogueServiceWeb

#endpoint = 'http://geoport.whoi.edu/csw'
#endpoint = 'http://www.ngdc.noaa.gov/geoportal/csw'
endpoint = 'http://data.ioos.us/csw'

csw = CatalogueServiceWeb(endpoint, timeout=60)
val = 'ROMS'
filter1 = fes.PropertyIsLike(propertyname='apiso:AnyText',literal=('*%s*' % val),
                        escapeChar='\\',wildCard='*',singleChar='?')
bbox = [-87.40, 34.25, -63.70, 66.70]    # [lon_min, lat_min, lon_max, lat_max]
bbox_filter = fes.BBox(bbox,crs='urn:ogc:def:crs:OGC:1.3:CRS84')
filter_list = [fes.And([filter1, bbox_filter])]
csw.getrecords2(constraints=filter_list, maxrecords=1000)
print("Number of datasets available: {}".format(len(csw.records.keys())))
```
and I get back:
```
ExceptionReport: 'Invalid Constraint: Invalid Filter request: Reprojection error: Invalid srsName "urn:ogc:def:crs:OGC:1.3:CRS84": Invalid source projection'
```
which smells like an old version of pycsw.    What version are we using here?
Can it be updated?
Or is there some other problem?
(If i use one of the other endpoints, it works okay)

**Comment by lukecampbell** [comment]
We were tied to an older version of PyCSW for CKAN support. That may have changed since I bundled everything a while back.

I think it was version 1.8.0

**Comment by rsignell-usgs** [comment]
Hey, wait, we can check the getCaps, can't we?

Okay, let's see:
http://data.ioos.us/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities
reports back:
```
<!--  pycsw 1.8.4  -->
```
Yes, that's very old.

I think you are free to install whatever version of pycsw you want.    Data.gov (also CKAN/pycsw) reports back:
http://catalog.data.gov/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities
```
<!--  pycsw 1.10.3  -->
```
Can we upgrade please?   
Filipe @ocefpaf and I would like to try our workflows on the new endpoint, but we can't without a pycsw upgrade.

Thanks!

**Comment by rsignell-usgs** [comment]
I'm going to raise upgrading pycsw as a new issue.

**Comment by ocefpaf** [comment]
@rsignell-usgs I believe the right repository for that new issue should be:

https://github.com/ioos/ckanext-ioos-theme/tree/master/ckanext-ioos_theme

Is that correct @lukecampbell?

**Comment by lukecampbell** [comment]
yes

**Comment by rsignell-usgs** [comment]
So all new catalog issues are going to be discussed in:
https://github.com/ioos/ckanext-ioos-theme/tree/master/ckanext-ioos_theme
@dpsnowden were just talking yesterday about where to discuss catalog issues. 
So now we have 3 repos:
* registry
* catalog
* ckanext-ioos-theme

**Comment by lukecampbell** [comment]
ioos/catalog is the older project which is hosted at http://catalog.ioos.us/ A portion of the project will remain active to perform service monitoring and the project will be renamed to "service-monitor"

ioos/registry is a documentation project for hosting on github.io  It was also used to log issues by data providers to update WAFs and services for NGDC to harvest.

ioos/ckanext-ioos-theme is a CKAN plugin and docker bundle project to run the new IOOS Catalog hosted at http://data.ioos.us/  For issues pertaining to http://data.ioos.us/ or the new catalog, issues should be logged here. Once ioos/catalog is renamed, this project will be an alias for ioos/catalog.

**Comment by rsignell-usgs** [comment]
Okay, thanks for the clarification.
