### ISSUE TITLE
How can I get a list of WAF endpoints that the catalog is harvesting?

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/catalog#52]
@benjwadams, you wrote: 
> https://data.ioos.us/harvest has the list of WAFs we harvest from. I don't know if there is access to this information through the CKAN API as well.

That page is useful in that it tells me the catalog harvests from WAF 19 endpoints, but what I'm looking for are the actual endpoints themselves, like:
```
http://www.neracoos.org/WAF/UMaine/iso/
http://www.pacioos.hawaii.edu/metadata/iso/
...
```
Where can I obtain such a list?

**Comment by rsignell-usgs** [comment]
I just discovered a list here:
https://github.com/ioos/catalog/blob/master/doc/ioos_registry_wafs.csv
but I think it's not up to date because some endpoints like 
http://thredds.axiomalaska.com/iso/unidata/
are giving 404 errors. 

@mwengren, could I get an updated list like this?   

Basically I'd just like to know what endpoints are currently populating:
https://registry.ioos.us/waf/

**Comment by mwengren** [comment]
Yes, there is this page available on the Registry: https://registry.ioos.us/about. 

But I suspect you probably want this (https://registry.ioos.us/api/v1/Harvests) from the [API](https://ioos.github.io/catalog/pages/registry/api/).
