### ISSUE TITLE
Follow GCOOS CS-W service deployment and assist with Catalog harvesting if necessary.

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog#55]
GCOOS will be deploying a CS-W service to add new data services (WMS/WCS).  Assist if necessary with CS-W harvest by the Harvest Registry, as we are not yet actively using the CS-W harvest pathway.

**Comment by benjwadams** [comment]
Do we have a URL to use?  I could just set up a CSW harvest source in CKAN.

**Comment by mwengren** [comment]
Pinging @fgayanilo in case they have the CS-W up for testing.   Felimon can register the CS-W URL in the Registry, this was more for tracking in case there are issues.  GCOOS may not be ready yet for this step.

**Comment by fgayanilo** [comment]
we have the CS-W installed and being tested at the moment. We discovered few issues that we hope to fix before the end of this month.

http://gcoosmaps.tamu.edu:8080/geoportal
http://gcoosmaps.tamu.edu:8080/geoportal/csw

**Comment by benjwadams** [comment]
@fgayanilo, where does this stand at the moment?

**Comment by fgayanilo** [comment]
Shin Kobara will work on removing some maps that may not need to be there. We should be ready before the end of the week. The URL remains the same.

**Comment by fgayanilo** [comment]
I will add this CS-W endpoint (http://gcoosmaps.tamu.edu:8080/geoportal/csw) to the harvester but it failed to harvest. Any idea?

**Comment by benjwadams** [comment]
In https://registry.ioos.us/waf/GCOOS/, tthere are couple zero-length XML files.  My hunch is that these could be causing a problem.

**Comment by fgayanilo** [comment]
If we can resolve this from your end, this will be great because the harvester will be robust enough and use ESRI/ArcGIS outputs as is. Having said that, we will try to eliminate the zero-length XML files from the manifest as requested.

**Comment by benjwadams** [comment]
@fgayanilo, I ran the harvest scripts manually.  I'm having issues making POST requests for getRecords calls to your CSW.

This GET request works fine and returns records as XML as expected:

http://gcoosmaps.tamu.edu:8080/geoportal/csw?service=CSW&request=GetRecords&startPosition=1&maxRecords=100&resultType=results&elementSetName=full&outputFormat=application/xml

Although the getCapabilities document seems to indicate they are enabled, POST requests seem to be encountering issues.  I first tried via OWSLib and later recreated the same request in cURL.  I received a 405 Method Not Allowed error payload from the following request:

```
curl -XPOST -d '<csw:GetRecords xmlns:atom="http://www.w3.org/2005/Atom" xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dct="http://purl.org/dc/terms/" xmlns:dif="http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/" xmlns:draw="gov.usgs.cida.gdp.draw" xmlns:fes="http://www.opengis.net/fes/2.0" xmlns:fgdc="http://www.opengis.net/cat/csw/csdgm" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gm03="http://www.interlis.ch/INTERLIS2.3" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gmi="http://www.isotc211.org/2005/gmi" xmlns:gml="http://www.opengis.net/gml" xmlns:gml311="http://www.opengis.net/gml" xmlns:gml32="http://www.opengis.net/gml/3.2" xmlns:gmx="http://www.isotc211.org/2005/gmx" xmlns:gts="http://www.isotc211.org/2005/gts" xmlns:ogc="http://www.opengis.net/ogc" xmlns:om="http://www.opengis.net/om/1.0" xmlns:om10="http://www.opengis.net/om/1.0" xmlns:om100="http://www.opengis.net/om/1.0" xmlns:om20="http://www.opengis.net/om/2.0" xmlns:ows="http://www.opengis.net/ows" xmlns:ows100="http://www.opengis.net/ows" xmlns:ows110="http://www.opengis.net/ows/1.1" xmlns:ows200="http://www.opengis.net/ows/2.0" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:rim="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0" xmlns:sa="http://www.opengis.net/sampling/1.0" xmlns:sml="http://www.opengis.net/sensorML/1.0.1" xmlns:sml101="http://www.opengis.net/sensorML/1.0.1" xmlns:sos="http://www.opengis.net/sos/1.0" xmlns:sos20="http://www.opengis.net/sos/2.0" xmlns:srv="http://www.isotc211.org/2005/srv" xmlns:swe="http://www.opengis.net/swe/1.0.1" xmlns:swe10="http://www.opengis.net/swe/1.0" xmlns:swe101="http://www.opengis.net/swe/1.0.1" xmlns:swe20="http://www.opengis.net/swe/2.0" xmlns:swes="http://www.opengis.net/swes/2.0" xmlns:tml="ttp://www.opengis.net/tml" xmlns:wcs="http://www.opengis.net/wcs" xmlns:wfs="http://www.opengis.net/wfs" xmlns:wfs20="http://www.opengis.net/wfs/2.0" xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:wps100="http://www.opengis.net/wps/1.0.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xs2="http://www.w3.org/XML/Schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" outputSchema="http://www.isotc211.org/2005/gmd" outputFormat="application/xml" version="3.0.0" servic$="CSW" resultType="results" startPosition="1" maxRecords="100" xsi:schemaLocation="http://www.opengis.net/cat/csw/2.0.2 http://schemas.opengis.net/csw/2.0.2/CSW-discovery.xsd"><csw:Query typeNames="csw:Record"><csw:ElementSetName>full</$sw:ElementSetName></csw:Query></csw:GetRecords>' http://gcoosmaps.tamu.edu:8080/geoportal/csw
```

**Comment by fgayanilo** [comment]
@benjwadams we will check tomcat config if POST is restricted or part of the <Limit> directive. I'll report back as soon as we can safely access the server. If you have ideas on what we should be checking as well, let us know.

**Comment by benjwadams** [comment]
More succintly, the request could also be written as:

`curl -XPOST -d '<csw:GetRecords xmlns:atom="http://www.w3.org/2005/Atom" xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" outputSchema="http://www.isotc211.org/2005/gmd" outputFormat="application/xml" version="2.0.2" service="CSW" resultType="results" startPosition="1" maxRecords="100" xsi:schemaLocation="http://www.opengis.net/cat/csw/2.0.2 http://schemas.opengis.net/csw/2.0.2/CSW-discovery.xsd"><csw:Query typeNames="csw:Record"><csw:ElementSetName>full</csw:ElementSetName></csw:Query></csw:GetRecords>'`

OWSLib attached a lot of namespacing information.

**Comment by fgayanilo** [comment]
@benjwadams the version may be causing the issue. Your calls are using CSW 2.0.2 and GCOOS is using version 3.0 of CSW. The schema references are at http://schemas.opengis.net/cat/csw/3.0/

**Comment by benjwadams** [comment]
@fgayanilo, I changed the XML payload to use the CSW 3.0 references.  I'm still getting HTTP 405 errors, indicating the POST method might be disabled.  Can you check your Tomcat directory for any XML config files where PUT, POST, GET, etc handling is defined?  A command like `fgrep --color -R -C5 POST --include='*.xml' .` run in the Tomcat directory might be helpful; here's a run on one of our servers, which does allow POST:

```/var/tomcats/tomcat-thredds# fgrep --color -R -C5 POST --include='*.xml' .                     
./webapps/thredds/WEB-INF/web.xml-    <error-code>500</error-code>
./webapps/thredds/WEB-INF/web.xml-    <location>/WEB-INF/jsp/errorpages/500.jsp</location>
./webapps/thredds/WEB-INF/web.xml-  </error-page>
./webapps/thredds/WEB-INF/web.xml-
./webapps/thredds/WEB-INF/web.xml-  <!-- ++++++++++ Setup security restrictions ++++++++++ -->
./webapps/thredds/WEB-INF/web.xml:  <!-- Default is to not allow DELETE, PUT, POST -->
./webapps/thredds/WEB-INF/web.xml-  <security-constraint>
./webapps/thredds/WEB-INF/web.xml-    <web-resource-collection>
./webapps/thredds/WEB-INF/web.xml-      <web-resource-name>not allowed</web-resource-name>
./webapps/thredds/WEB-INF/web.xml-      <url-pattern>/*</url-pattern>
./webapps/thredds/WEB-INF/web.xml-      <http-method>DELETE</http-method>
./webapps/thredds/WEB-INF/web.xml-      <http-method>PUT</http-method>
./webapps/thredds/WEB-INF/web.xml:      <!-- http-method>POST</http-method -->
./webapps/thredds/WEB-INF/web.xml-    </web-resource-collection>
./webapps/thredds/WEB-INF/web.xml-    <auth-constraint/>
./webapps/thredds/WEB-INF/web.xml-  </security-constraint>
./webapps/thredds/WEB-INF/web.xml-
./webapps/thredds/WEB-INF/web.xml-  <!-- This allows "remote configuration":
--
./webapps/thredds/WEB-INF/web.xml-    <user-data-constraint>
./webapps/thredds/WEB-INF/web.xml-      <transport-guarantee>CONFIDENTIAL</transport-guarantee>
./webapps/thredds/WEB-INF/web.xml-    </user-data-constraint>
./webapps/thredds/WEB-INF/web.xml-  </security-constraint>
./webapps/thredds/WEB-INF/web.xml-
./webapps/thredds/WEB-INF/web.xml:  <!-- Setup security restrictions on THREDDS server HTTP POST capabilities in CatalogGen. -->
./webapps/thredds/WEB-INF/web.xml-  <security-constraint>
./webapps/thredds/WEB-INF/web.xml-    <web-resource-collection>
./webapps/thredds/WEB-INF/web.xml-      <web-resource-name>cataloggen configuration</web-resource-name>
./webapps/thredds/WEB-INF/web.xml-      <url-pattern>/cataloggen/admin/*</url-pattern>
./webapps/thredds/WEB-INF/web.xml-      <http-method>GET</http-method>
./webapps/thredds/WEB-INF/web.xml:      <http-method>POST</http-method>
./webapps/thredds/WEB-INF/web.xml-    </web-resource-collection>
./webapps/thredds/WEB-INF/web.xml-    <auth-constraint>
./webapps/thredds/WEB-INF/web.xml-      <role-name>tdsConfig</role-name>
./webapps/thredds/WEB-INF/web.xml-    </auth-constraint>
./webapps/thredds/WEB-INF/web.xml-    <user-data-constraint>
--
./conf/web.xml-
./conf/web.xml-
./conf/web.xml-  <!-- ================== Built In Filter Definitions ===================== -->
./conf/web.xml-
./conf/web.xml-  <!-- A filter that sets character encoding that is used to decode -->
./conf/web.xml:  <!-- parameters in a POST request -->
./conf/web.xml-<!--
./conf/web.xml-    <filter>
./conf/web.xml-        <filter-name>setCharacterEncodingFilter</filter-name>
./conf/web.xml-        <filter-class>org.apache.catalina.filters.SetCharacterEncodingFilter</filter-class>
```

**Comment by fgayanilo** [comment]
@benjwadams Shin'ichi Kobara made few configuration changes based on ESRI recomms. 
http://gcoosmaps.tamu.edu:8080/geoportal/csw?service=CSW&request=GetCapabilities&version=3.0.0

Just in case, also try the base instance at:  http://gcoosmaps.tamu.edu:8080/geoportal-search/csw?service=CSW&request=GetCapabilities&version=3.0.0

Give it another try.

**Comment by fgayanilo** [comment]
@benjwadams I am in MD for the 2018 ESIP meeting but I'll try this when I return next week.

**Comment by fgayanilo** [comment]
@benjwadams have you seen this issue: https://github.com/Esri/geoportal-server-catalog/issues/67

**Comment by benjwadams** [comment]
@fgayanilo, in reviewing open issues for the upcoming milestone, I reissued a GetRecords request over POST.  Instead of getting records back in the XML payload, I'm getting a GetCapabilities document back from the server.  Please check on your end if there is some kind of request redirection occurring on the server.

**Comment by mwengren** [comment]
Moving milestone to next release since there hasn't been any change on the GCOOS side to allow our CS-W harvest requests.  

FYI @fgayanillo, please take a look at your server firewall settings because we are not able to issue the HTTP POST requests necessary to harvest from your CS-W.  Until this is resolved, we won't be able to include your CS-W hosted records in the Catalog.

**Comment by otwn** [comment]
Can you try to harvest from this?
http://geo.gcoos.org:8080/geoportal/csw

gcoosmaps server is no longer available and I switched server to this one.

**Comment by benjwadams** [comment]
Still appears to be eating the POST request:

`curl -XPOST -d '<csw:GetRecords xmlns:atom="http://www.w3.org/2005/Atom" xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" outputSchema="http://www.isotc211.org/2005/gmd" outputFormat="application/xml" version="2.0.2" service="CSW" resultType="results" startPosition="1" maxRecords="100" xsi:schemaLocation="http://www.opengis.net/cat/csw/2.0.2 http://schemas.opengis.net/csw/2.0.2/CSW-discovery.xsd"><csw:Query typeNames="csw:Record"><csw:ElementSetName>full</csw:ElementSetName></csw:Query></csw:GetRecords>' http://geo.gcoos.org:8080/geoportal/csw`

Returns a `GetCapabilities` document.

**Comment by otwn** [comment]
I see. We are working on this, but data source of this is arcgis server and it has an issue now. As soon as we solve this issue, I will post the new url again.

**Comment by mwengren** [comment]
@otwn @fgayanillo what is the status of the GCOOS CS-W service debugging?  We need your assistance to debug server issues to enable the harvest or we will have to close this issue as unneeded.

**Comment by fgayanilo** [comment]
We still cannot figure out the problem and we may need to return on this at some future time.

**Comment by mwengren** [comment]
@fgayanilo Ok, I think we'll close this issue out for now.  It would be good to include the GCOOS GIS data in the future, so if you decide to pick it back up please reach out to us for any troubleshooting help.

**Comment by mwengren** [comment]
Closing #55.
