### ISSUE TITLE
NDBC and CO-OPS WAFs no longer updating

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog#58]
The [CO-OPS](https://data.ioos.us/stations/waf/co-ops/) and [NDBC](https://data.ioos.us/stations/waf/ndbc/) WAFs haven't updated since Aug 31.  

We need to figure out why the sensorml2iso WAF generation scripts stopped and restart the cron or whatever config that was running them originally.  

@benjwadams I remember you saying there were a lot of repeated processes handling WAF scripting around then, maybe we never found a stable approach when trying to fix that issue?

I set up a couple simple cron shell scripts on my personal account that are maintaining NDBC and SCRIPPS HFRadar WAFs that run daily: https://data.ioos.us/mwengren/hf_radar_dac_ndbc/.  

I think the sensorml2iso processes were Dockerized by Luke, so different set up...

**Comment by benjwadams** [comment]
The container was indeed running, but it ran into an error condition which was not logged.  Only when I ran it manually did I discover it was getting stuck writing a file.  I'll update with any more info as I fix this.

**Comment by benjwadams** [comment]
It looks like at least the <gmd:dateStamp> element has updated in a number of the HFRadar datesets.  I'll check to see that it's propagating through to catalog, etc.

**Comment by mwengren** [comment]
Looks to be updating again this morning.  If you think the underlying issue is resolved with the Docker processes, let's close this issue.

**Comment by mwengren** [comment]
I'm reopening this issue since [CO-OPS](https://data.ioos.us/stations/waf/co-ops/) and [NDBC](https://data.ioos.us/stations/waf/ndbc/) WAFs are frozen since some time in Nov/Dec.  

Can we add some sort of error notification if these cron jobs fail again (if not too onerous).  Seems like we're continually having to kick the tires to keep this process up and running, and there's no notice when it fails.

**Comment by benjwadams** [comment]
The container hung due to excessive amounts of logs being generated within the container.  I have since moved the logs into a separate volume, but the log contents are still pretty excessive, so the logging should be configurable.  I created an issue for sensorml2iso here:

https://github.com/ioos/sensorml2iso/issues/24

**Comment by brianmckenna** [comment]
@mwengren these WAFs look to still be updating, good to close?

**Comment by mwengren** [comment]
@benjwadams Let's upgrade sensorml2iso version (1.0.4 released today), disable the verbose logging, and monitor the NDBC WAF to make sure everything looks good in terms of XML being output, and then close this and ioos/catalog#63 out together.

**Comment by benjwadams** [comment]
I just pulled the latest image onto production, the verbose logging appears disabled by default.  Let's check the output tomorrow.

**Comment by mwengren** [comment]
@benjwadams How's this look?  Is the logging reduced?  Can we close this one out?
