### ISSUE TITLE
Promote opendap service to top level

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/catalog#6]
When I find datasets that have OPeNDAP endpoints, those endpoints don't appear at the top level along with other services such as WCS.  Can the OPeNDAP endpoints be promoted to the entry level?

For example the first dataset here doesn't appear to have an OPeNDAP service:
![2016-08-12_9-04-41](https://cloud.githubusercontent.com/assets/1872600/17623157/a2992940-606c-11e6-96ac-c19fb9c13b75.jpg)
But if we click on the dataset can see that there is *indeed* an OPeNDAP service:
![2016-08-12_9-05-16](https://cloud.githubusercontent.com/assets/1872600/17623182/ce93f98a-606c-11e6-84de-09b1ffce19df.jpg)

**Comment by mwengren** [comment]
I've looked into doing this for the NOAA Catalog.  It should be a combination of making different XPath search strings for resource type instances here: https://github.com/ckan/ckanext-spatial/blob/master/ckanext/spatial/model/harvested_metadata.py#L819-L833, as well as ordering the resulting matches here before they're persisted: https://github.com/ckan/ckanext-spatial/blob/master/ckanext/spatial/harvesters/base.py#L372-L396.  Not too difficult, but there's no functionality for CKAN to sort or modify the order of resources once they're added to the resource list and db, the entire record has to be reharvested (or maybe refreshed).

**Comment by rsignell-usgs** [comment]
@mwengren , they've done it on data.gov, so we could ask them how they did it.   @kalxas, do you know who to contact?

**Comment by lukecampbell** [comment]
Yeah, I think I know how to do it. I did this already with some of the style changes that I had to undo, those should be coming back in the near future. I LOVE how @mwengren found the exact spots that I'd need to change though, that makes this infinitely easier.

**Comment by benjwadams** [comment]
Should I call such a service found "DAP" or "OPeNDAP"?

**Comment by rsignell-usgs** [comment]
"OPeNDAP"!

**Comment by lukecampbell** [comment]
Yeah it's OPeNDAP.

**Comment by mwengren** [comment]
+1
