### ISSUE TITLE
SECOORA ERDDAP endpoints not found in catalog

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/catalog#64]
Thanks to https://github.com/ioos/catalog/issues/62#issuecomment-409696108 we can now find `ERDDAP:tabledap` endpoints, but the SECOORA ERDDAP endpoints are not showing up. 

If we take a look at the ISO records from the SECOORA ERDDAP:
http://erddap.secoora.org/erddap/metadata/iso19115/xml/
we can see, for example, that there should be a dataset discoverable with a free text search on "Whitepoint".  (the 3rd record).

But if we look for "Whitepoint" in the IOOS Catalog:
https://data.ioos.us/dataset?q=Whitepoint
we find nothing.   

So we can't even see it from CKAN, let alone pycsw.  

Can we take a look and see if the harvest is failing, or the records are getting rejected for some reason?

How do we do this?

**Comment by benjwadams** [comment]
Looking into this, it looks like the CKAN harvests for SECOORA complete successfully.

However, the Registry's harvester may be stuck on the SECOORA ERDDAP WAF: https://registry.ioos.us/harvests  (search for SECOORA)

**Comment by mwengren** [comment]
Strange, I see it's still running.  This definitely worked at one time without issue when @kwilcox created it.  Did you do a manual reharvest today @benjwadams?  Maybe it is just slower than normal chugging through the ~2300 records... if not we may need to dive into the MeteorJS code to diagnose what's happening with the job queue.

**Comment by rsignell-usgs** [comment]
![2018-08-02_13-05-10](https://user-images.githubusercontent.com/1872600/43599168-c2f1be6c-9654-11e8-9a0a-f3293215f0c6.png)

**Comment by benjwadams** [comment]
@mwengren, the harvesting code itself is running via Python.

@rsignell-usgs, Regarding the 0 records -- I restarted the harvester and it ran into an error condition, which then reset the record count on registry to zero.  I'm tracking that down right now -- another thing is that the harvest type likely should be "ERDDAP-WAF" for records coming from ERDDAP's XML metadata endpoint.
```
Here's the last error traceback I could find from one of the harvester processes:
2018-08-02 16:57:59,257 - catalog_harvesting - ERROR - Failed to successfully harvest http://erddap.secoora.org/erddap/metadata/iso19115/xml/
Traceback (most recent call last):
  File "/opt/catalog-harvesting/catalog_harvesting/harvest.py", line 72, in download_harvest
    records, errors = download_waf(db, harvest, src, path)
  File "/opt/catalog-harvesting/catalog_harvesting/harvest.py", line 218, in download_waf
    for link in waf_parser.parse():
  File "/opt/catalog-harvesting/catalog_harvesting/waf_parser.py", line 41, in parse
    self._parse(self.url, documents, 0, maxdepth)
  File "/opt/catalog-harvesting/catalog_harvesting/waf_parser.py", line 85, in _parse
    self._parse(link, documents, depth + 1, maxdepth)
  File "/opt/catalog-harvesting/catalog_harvesting/waf_parser.py", line 85, in _parse
    self._parse(link, documents, depth + 1, maxdepth)
  File "/opt/catalog-harvesting/catalog_harvesting/waf_parser.py", line 65, in _parse
    if link.startswith('..'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by kwilcox** [comment]
There was some change a few months ago that should have allowed ERDDAP WAFs to function identically to regular WAFs. @mwengren knows the details...

**Comment by mwengren** [comment]
Hi @benjwadams right, now I remember :) the harvesting is Python.

Like @kwilcox just said...

We had an issue about this at point I think, but I believe due to recent changes in the way ERDDAP does WAFs, the appropriate way to harvest newer releases like SECOORA's is to just use the plain WAF harvest type.  I think we actually were going to re-classify the ERDDAP WAF type to have a '<= 1.82' in the label (or whatever the relevant release was) because using ERDDAP WAF type on newer once *may* not work.

Oooh, I found the issue I was thinking of: https://github.com/ioos/catalog-harvest-registry/issues/116

**Comment by benjwadams** [comment]
Duly noted.  I'm going to attempt to debug what's occurring on the SECOORA WAF harvest on my local dev environment.

**Comment by rsignell-usgs** [comment]
The harvesting of the SECOORA and NERACOOS ERDDAP endpoints are both showing 0 records harvested, and both show the error "Cannot Access API [500]" as CKAN Job status.   Or is that just a special message for me because I don't have access?

**Comment by rsignell-usgs** [comment]
CENCOOS ERDDPA is looking good, however.   Let's have what they are having!  😸 

![2018-08-02_15-50-53](https://user-images.githubusercontent.com/1872600/43607361-fbb31fae-966b-11e8-9779-7c928d4af14b.png)

**Comment by mwengren** [comment]
@rsignell-usgs The CKAN Job Status/500 Cannot Access API message is another issue we need to address, see: https://github.com/ioos/catalog-harvest-registry/issues/118.

From my observation, it seems to come and go, so hopefully it's an environment issue and not a newly-introduced bug.  The Registry is supposed to have access to read status and trigger CKAN harvests on demand.

**Comment by benjwadams** [comment]
So what is essentially happening is that the `WAFParser` class will get any <a> elements on a page.  There are a number of links on most ERDDAP endpoints, i.e. about NOAA, NMFS, etc and presumably those don't want to be harvested, nor harvested.  A bunch of links that have nothing to do with ISO 19115 XML metadata are returned, including some anchors without an href attribute, which causes the parser to bomb.

https://github.com/ioos/catalog-harvesting/blob/master/catalog_harvesting/waf_parser.py#L26-L31

So unfortunately, we can't just drop in the regular WAF parser as it is presently written.

By comparison, here is the ERDDAP link parser was written prior to the release of ERDDAP 1.82 and looks for links contained with a `<pre>` element.

https://github.com/ioos/catalog-harvesting/blob/master/catalog_harvesting/erddap_waf_parser.py#L16-L21

Because ERDDAP has a version string near the footer, my approach is likely going to be to try to parse that version and adjust the ERDDAP WAF parser accordingly.

**Comment by rsignell-usgs** [comment]
@benjwadams , so why is the CENCOOS ERDDAP working with `WAFParser`?

**Comment by benjwadams** [comment]
This
> A bunch of links that have nothing to do with ISO 19115 XML metadata are returned, including some anchors without an href attribute, which causes the parser to bomb.
It's possible to have a `<a>` with `href` attribute and it looks like it's crawling from mutliple links in the default implementation
https://github.com/ioos/catalog-harvesting/blob/master/catalog_harvesting/waf_parser.py#L65-L66
So it's trying to call a string method on None, which is going to fail.

Also by using the default parser you may end up with some XML links which aren't ISO metadata related to the source that's being harvested.

I'm going to push up fixes to the default parser to handle these empty links as well as conditional handling of the ERDDAP XML link table depending on the version of ERDDAP parsed out from the footer.

**Comment by benjwadams** [comment]
Didn't mean to close there, sorry.

**Comment by benjwadams** [comment]
OK, the SECOORA ERDDAP WAF is now harvesting on the registry, see https://github.com/ioos/catalog-harvesting/pull/51

This also applies to the NERACOOS ERDDAP content, which had ERDDAP 1.82 and had encountered similar issues.

I'm kicking off a reharvest in CKAN right now and hopefully records should soon propagate to CKAN and PyCSW.

**Comment by benjwadams** [comment]
> The harvesting of the SECOORA and NERACOOS ERDDAP endpoints are both showing 0 records harvested, and both show the error "Cannot Access API [500]" as CKAN Job status. Or is that just a special message for me because I don't have access?

@rsignell-usgs, this was a separate issue having to do with API keys for CKAN and was fixed.  I can't find the issue at the moment, but I'll update this comment with the fix resolution when I find it again.

**Comment by mwengren** [comment]
Alright, great news @benjwadams!  Great to fix something on a Friday afternoon.  Thanks for all the troubleshooting this week.

**Comment by rsignell-usgs** [comment]
Woohoo!   Working!   Nice work @benjwadams !!!
![2018-08-03_18-00-13](https://user-images.githubusercontent.com/1872600/43667710-2607fa0a-9747-11e8-877c-8f581a670994.png)

**Comment by ocefpaf** [comment]
Awesome! I can see many station from SECOORA on my notebook now:

http://nbviewer.jupyter.org/gist/ocefpaf/37bc91ce93d7fd198850201b3ae0da8b

I know that @emiliom will be demoing a similar notebook for the NANOOS region.
@emiliom are you getting the ERDDAP:tabledap endpoints on your example?
If not we need to apply some of these corrections there.

**Comment by rsignell-usgs** [comment]
@benjwadams, this seems broken again.  I just tried the same search and the links have gone missing:

![2020-05-19_6-54-34](https://user-images.githubusercontent.com/1872600/82318350-b2637880-999d-11ea-9b06-c25038bcb744.png)

Full notebook is here: https://gist.github.com/rsignell-usgs/3f2f8f9b2f6718e34df3e7095ff6c27b

cc @ocefpaf, @emiliom

**Comment by mwengren** [comment]
I noticed this issue again today by accident (can someone tell me why GitHub Projects doesn't automatically add new issues opened or reopened on a repo to a project dashboard??).  

Anyway, I ran the notebook above and was able to find the Whitepoint station with four ERDDAP resource links.  So, I think all is well again, closing this issue.  

Related to this, I discovered recently in ioos/catalog-harvest-registry#137 the `ERDDAP WAF` type is the best option to use to harvest from ERDDAP in most situations, FWIW.

Output from final notebook cell:

```
1
title:Whitepoint Swash
identifier:edu_ccu_lbos_148
modified:2020-10-05
[{'scheme': 'order',
  'url': 'http://erddap.secoora.org/erddap/tabledap/edu_ccu_lbos_148.html'},
 {'scheme': 'order',
  'url': 'http://erddap.secoora.org/erddap/tabledap/edu_ccu_lbos_148.graph'},
 {'scheme': 'ERDDAP:tabledap',
  'url': 'http://erddap.secoora.org/erddap/tabledap/edu_ccu_lbos_148'},
 {'scheme': 'OPeNDAP:OPeNDAP',
  'url': 'http://erddap.secoora.org/erddap/tabledap/edu_ccu_lbos_148'}]
```
