### ISSUE TITLE
CKAN 2.8 Upgrade

### ISSUE THREAD

**Issue by benjwadams** [ioos/catalog#65]
Upgrade the version of CKAN to 2.8.   Because of the changes in the base CKAN Dockerfile, this will also require rewriting of CKAN's Docker setup.

**Comment by benjwadams** [comment]
Current WIP branch is here with a compose file under

https://github.com/benjwadams/ckan/blob/new_compose_test/contrib/docker/docker-compose.yml

Known issues so far (will create separate issues for tracking purposes):

Styling seems broken on home page after upgrades

ckanext-spatial had some custom extensions made to the metadata model on the IOOS branch  -- these will need to be brought up to date with the current branch or refactored to make a class which extends the original metadata model somehow.

**Comment by benjwadams** [comment]
Changing back to using Bootstrap 2 and associated templates fixed the wonky styling problems.  Apparently CKAN 2.8 went to using Bootstrap 3 as a default and it initially caused all the custom templates to look out of whack.  Reverting to the Bootstrap 2 templates/CSS fixed things.

http://docs.ckan.org/en/2.8/maintaining/configuration.html#ckan-base-templates-folder

**Comment by benjwadams** [comment]
@mwengren: I have a draft version of the new branch here with updated README including build instructions.  https://github.com/benjwadams/catalog-docker-base/tree/new_ckan_version_draft
You're free to attempt building catalog if you want.

It uses a custom CKAN branch with some mostly Docker build related changes as a submodule.  The approach may seem a little strange, but it is a lot easier than the current production build process where we have to go through a bunch of different repos and rebuild many images every time there is a change.

I hope to have the changes deployed to a dev server in the next week or so in order to test harvesting, the frontend components, etc.

**Comment by benjwadams** [comment]
@mwengren: I was able to fix the issues with the [dropdown menus not operating](https://github.com/ioos/catalog-ckan/commit/8c2dcfc8c980d1d41295d25733e05b3290c54de7) and [pagination CSS/display](https://github.com/ioos/catalog-ckan/commit/dcc8830aa06bd339197e957ac631195b3f6e371f).  I believe the latter may be a bug/omission in newer versions of CKAN when using the legacy Bootstrap 2 templates, so I may make a bug report to CKAN.  Tomorrow I will merge the new CKAN version branches into master, tag things for release, etc and we should be good to close this issue and the milestone soon thereafter.

**Comment by mwengren** [comment]
@benjwadams, things are looking good.  The only remaining UI issue I noticed this morning was that the draw icon is missing from the Leaflet map.  See screenshot.  Resource dropdowns and pagination controls look better.

![Screenshot from 2018-09-26 09-13-35.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/573c586fa6fa830e003f504b/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f3723dd7b568ef1b36505c424da953444d04bea6d37ef5f22e7a98590ce5d86d5d74953b45a4bf8218bb01ba21884b8db6bd895edcfa7f74b9dfd0126754505a9bf54f37a0934acd5bf142e74a52ad1b336be7647b.png)

**Comment by benjwadams** [comment]
@mwengren I am unable to replicate the above issue with the map.  Since the new version is now deployed to the production site, could you see if it's working on data.ioos.us for you?
![map_icon_ff_63](https://user-images.githubusercontent.com/4118886/46172032-5c920800-c270-11e8-9503-29784c4391c8.PNG)

**Comment by benjwadams** [comment]
Closing this out as I now have a release and all major issues appear addressed.
