### ISSUE TITLE
Enable CORS on CSW requests

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/catalog#70]
It appears CORS is not enabled on https://data.ioos.us/csw. 

This makes exploring IOOS datasets by CSW in tools like TerriaJS fail. 

CORS compliance can be tested at https://test-cors.org:  If you drop the CSW endpoint in there under Server=>Remote URL, and hit "Send Request", it should return 200, not 0.

https://gamone.whoi.edu/csw    returns 200.
https://data.ioos.us/csw    returns 0.

Looks like CORS can be configured here?
https://github.com/brew/ckan/commit/0d97844a7d3c6be8efbdf7df9412dc2ab8bd9335#diff-3190ec7edf77111f1fecaa5d4877ba0eR81

**Comment by mwengren** [comment]
@benjwadams Can you take a look at this?

**Comment by rsignell-usgs** [comment]
As I understand it, for a public server that doesn't require/support any authentication, enabling CORS is definitely 100% safe

**Comment by benjwadams** [comment]
Try it now.  There appears to have been a misconfiguration issue with the web server.

PS: for server configuration issues, it's often better to reach me directly via email.

**Comment by rsignell-usgs** [comment]
Yes!  Passes the CORS test:
![2018-11-08_5-58-03](https://user-images.githubusercontent.com/1872600/48194552-584f1500-e31b-11e8-97a5-b083cacc8b48.png)
