### ISSUE TITLE
GLOS WAFs need attention

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog#71]
The GLOS TDS WAF has moved.  No records found at the former URL: http://tds.glos.us/waf/.  

Perhaps a side-effect of the cloud migration?

**Comment by mwengren** [comment]
Resolve duplicative fileIdentifier issues in #68 at the same time as this issue.

**Comment by benjwadams** [comment]
Updated to use GLOS GeoNetwork CSW as data source for harvest in the Harvest Registry.  Records are showing up in GLOS WAF and are harvested by the Catalog, so I'm going to close this out.
