### ISSUE TITLE
Fix sync process for IOOS Catalog WAF (https://data.ioos.us/waf).

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog#79]
IOOS Catalog currently has ~ 21000 datasets.

NOAA/Data.gov harvest reports that read from the Catalog WAF (https://data.ioos.us) report that it contains around 31,000 datasets, when it should contain no more than the ~ 21,000 in the Catalog itself.  Let's see what's going on.

Some related links from NOAA:

* Processing complete. You can view the results at: https://data.noaa.gov/waf/NOAA/ioos//iso/
* To ensure that all records passed validation and to check other diagnostics, view the reports at the bottom of the index page or browse reports at https://data.noaa.gov/waf/NOAA/ioos//iso/reports/

| Title | WAF URL | Records in Source | Records in Error | Records in Catalog | Error Rate | Error Notes | Status Notes
| -- | -- | -- | -- | -- | -- | -- | -- |
IOOS | https://data.noaa.gov/waf/NOAA/ioos/iso/xml/ | 32167 | 4746 | 27421 | 14.75425125 | Unknown | Started harvest at 3:15 MT 9/18/2020, current error rate is 0.1%. Sandbox system not built to handle this large of harvest source, production expected to be fine

**Comment by mwengren** [comment]
Also, in the NOAA WAF spreadsheet, we have the most records by roughly 15K (more than the largest NESDIS WAF by far), so we should try to reduce this closer to the real amount ASAP.

**Comment by mwengren** [comment]
Record counts as of 1/5/21:

**IOOS Data Catalog** (https://data.ioos.us/dataset): 13,870

**IOOS WAF** (https://data.ioos.us/waf): 20,912

**NCEI/OneStop IOOS WAF** (https://data.noaa.gov/waf/NOAA/ioos//iso/xml/): 17,675

**NCEI/OneStop IOOS WAF Report** (https://data.noaa.gov/waf/NOAA/ioos//iso/): 13,385

It's not clear why the record count decreases between the IOOS WAF & NCEI WAF by ~3000 records, or why the NCEI report doesn't include all 17675 successfully harvested IOOS records from the NCEI WAF.  I have an email out to NOAA POCs to hopefully clear up why that's the case.  

@benjwadams I'd like to close this issue out, but since we still have a lingering sync issue between the IOOS Catalog and IOOS WAF, I think we need to figure out why those numbers aren't in line.

Once we have the CKAN harvesting issues sorted out, can you re-investigate?

**Comment by mwengren** [comment]
Counts as of 2/8/21:

IOOS Data Catalog (https://data.ioos.us/dataset): 13,607

IOOS WAF (https://data.ioos.us/waf): 20,912

NCEI/OneStop IOOS WAF (https://data.noaa.gov/waf/NOAA/ioos//iso/xml/): 17,675

It's unclear how frequently the NCEI/OneStop WAF is synced with the IOOS WAF, or whether this is automated or not.  

We still need to resolve why 20,912 doesn't match 13,607 as well.

**Comment by mwengren** [comment]
@benjwadams Goal here is to have the IOOS Data Catalog count match IOOS WAF count - WAF should reflect whatever is present in IOOS CKAN Catalog.

We can look into changing the frequency of the sync process to weekly if it helps with resource constraints.  Upstream NOAA/NCEI harvest doesn't happen more frequently than monthly if even that frequent, so we have some leeway.

From 2/8/21 Catalog meeting: IOOS WAF syncs from CS-W service/database, which doesn't delete records removed from CKAN source as is.  

Need to investigate alternatives or whether pycsw database sync process can be configured to remove non-existent CKAN records (old records that have been removed, for example).  Should be simple to do a table scan comparison between pycsw and CKAN db tables - from there figure out the best option to add a purge routine into the mix to drop old/orphaned pycsw records: monthly pycsw database truncate or routine process that compares table contents.

**Comment by mwengren** [comment]
@benjwadams Fixed the pycsw/CKAN/IOOS Centralized WAF sync issue, so our WAF and pycsw service now reflects Catalog dataset count better and should stay in sync going forward.

I sent an email to NOAA POCs about the harvest process from IOOS Centralized WAF to the NCEI IOOS WAF week of 3/1.  

They are going to look into why NCEI/OneStop processes haven't been routinely harvesting from the IOOS WAF.  

Current record count as of 3/4:

IOOS WAF (https://data.ioos.us/waf): 13048

NCEI/OneStop IOOS WAF (https://data.noaa.gov/waf/NOAA/ioos//iso/xml/): 17,675

When we have confirmation the NCEI IOOS WAF record count more closely matches the IOOS WAF, or when we release Catalog 1.6 March 22, we can close this issue out, whichever comes first.

**Comment by mwengren** [comment]
@benjwadams we still need to do this once CKAN 2.9 is fully functional and Registry harvests are migrated over. 

From meeting notes:
* Ben to look into populating WAF from CKAN database rather than CS-W database
* CS-W service has ongoing sync issues w/CKAN, not actively maintained

**Comment by mwengren** [comment]
This appears to be resolved based on recent NOAA harvest results I've seen.   Centralized WAF https://data.ioos.us/waf has ~35,000 records currently, which is in line with Catalog when it's working properly.

Let's confirm at next Catalog meeting and if so close this issue out then.

**Comment by mwengren** [comment]
@benjwadams Added a script to sync content from CKAN database to data.ioos.us/waf on a daily basis.  Reverse proxy currently in place from data.ioos.us (whose DNS is still pointing to Glider DAC server) to Catalog server to serve content at data.ioos.us/waf temporarily.  This is working well.  

This will be removed once Glider DAC FTP service is transitioned to SFTP (TBD).  We will close this issue once Glider DAC changes are in place.  @kbailey-noaa

**Comment by mwengren** [comment]
@benjwadams It looks like there haven't been any content updates in https://data.ioos.us/waf since ~ end of July, so this is still malfunctioning.

Has the data.ioos.us DNS been updated to point to the CKAN server, and not the Glider DAC server?  Have the proxy configs been removed as [mentioned above](https://github.com/ioos/catalog/issues/79#issuecomment-1638383378)?

NOAA OneStop is currently harvesting from https://data.ioos.us/waf on a weekly basis.  The past few weeks I've gotten harvest result emails that say 'no records to change', which tipped me off about the problem with the WAF.

To confirm I did a few comparison searches to find some recent Glider DAC datasets (having a minimum time coverage of 2023-05-01):

* Results from IOOS Catalog: https://data.ioos.us/dataset/?ext_timerange_start=2023-05-01T00%3A00%3A00Z&ext_timerange_end=&ext_min_depth=&ext_max_depth=&organization=glider-dac
* Results from OneStop (filtering by prefix 'ce-31' as a way to narrow down results for comparison of specific DAC datasets): https://data.noaa.gov/onestop/collections?q=ce_31*&tr=i&s=2023-05-01T00%3A00%3A00Z

In the IOOS Catalog, a new dataset matching the above filter criteria has been published from the DAC to IOOS Catalog: [ce_311-20230616t1819](https://data.ioos.us/dataset/ce_311-20230616t1819).  This appears in the IOOS Catalog search results above but doesn't in the OneStop results.  Searching https://data.ioos.us/waf for the dataset id also comes up empty, so the WAF update process and by extension harvest to OneStop are broken.   

Can you take a look?  

Also, are there any other server changes that need to be made to IOOS Catalog related to the data.ioos.us DNS change?

**Comment by mwengren** [comment]
Update from today's Catalog meeting: this is broken currently due to a firewall setting disabling the nginx proxy from the Glider DAC web server to IOOS Catalog server to host updated content at https://data.ioos.us/waf via proxy (or something like that).  This can be resolved pending Glider DAC/data.ioos.us DNS changes.

**Comment by benjwadams** [comment]
Record count is now much more in line with CKAN after DNS was moved and process restored.

**Comment by mwengren** [comment]
WAF sync process from CKAN runs daily per @benjwadams.  So, we should expect to see updated records on a daily basis according to content in CKAN.  

Closing for now since the issue appears resolved.
