### ISSUE TITLE
Fix SCCOOS-managed HF Radar DAC WAF

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog#80]
URL in Registry: https://sccoos.org/dr/metadata/ioos/hfradar/

SCCOOS/Vicky Rowley had been responsible for maintaining this WAF.  

Currently the HTML table structure in the script-generated page has structural issues - missing <tr> tags.  As a result, the Registry is unable to parse the malformed HTML so the harvest fails.

This should be a quick fix for someone with the data manager role at SCCOOS/UCSD to resolve, once that person is identified.

**Comment by benjwadams** [comment]
Link is 404, do we have an equivalent replacement link?

**Comment by mwengren** [comment]
Let's wait on resolving individual harvest WAF issues (404/dead links, etc) until we have the overall harvesting system running smoothly, per: ioos/ckanext-ioos-theme#238.  

There will be a number of individual WAFs that we'll need to work with providers to restore, but that's dependent on harvesting working reliably.

**Comment by mwengren** [comment]
Since the Scripps CORDC HFRNet service will be discontinued next June anyway, there's no longer a need to restore this WAF.

We should work with NDBC to generate a WAF for their future NCCF-based HFRNet TDS distribution service.
