### ISSUE TITLE
Issue with Harvest Registry for USGS ScienceBase source

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/catalog#83]
Hopefully I am capturing this well.

ScienceBase CSW harvest and the ISO XML validation step that the Registry performs is reporting errors for 65 datasets of the 204. This is mostly due to  dummy/placeholder URLs being added that are failing validation in CKAN (correctly or not). Trying to match the errors to the ScienceBase records is complicated, so we're holding off until the CKAN move is complete.

Logging here so we don't loose track of this thread.

cc @sformel-usgs

**Comment by benjwadams** [comment]
Likely related to #237.  Going to close this issue as this repo is Catalog related, not Registry.  Registry is also being transitioned away from.  However, both use the same harvester.
