### ISSUE TITLE
Error messages on metadata and feedback links

### ISSUE THREAD

**Issue by conniekot** [ioos/catalog#89]
Hi @mwengren, two links were giving 404 error messages on Chrome:
1) https://data.ioos.us/harvest/object/1189edea-23d7-4eb1-8a5e-4459c2bda0f7, which was from selecting ISO-19139 (Local) Metadata on the list here: https://data.ioos.us/dataset/rv-manta-fgbnms-fgbnms-15-26_get_into_your_sanctuary_day_1-nc-29-31n-94-82w-2015-06-27, and
2) Feedback tab: https://data.ioos.us/feedback/
Thanks!

**Comment by benjwadams** [comment]
1) We have to periodically clear out harvest objects as they run daily and are not cleaned up by default, leading to bloat, as the metadata XML is fetched every time.

2) We'll look into what's going on with the feedback.

**Comment by benjwadams** [comment]
Closing in favor of #269.

**Comment by mwengren** [comment]
xref ioos/ioos-us#269.

**Comment by nguyandy** [comment]
@mwengren @benjwadams 

Looks like the feedback page breaks if there is a trailing slash
https://data.ioos.us/feedback/
vs
https://data.ioos.us/feedback
