### ISSUE TITLE
CKAN search performance/PG database bloat

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog#90]
Catalog has been performing slowly in search results, page load times, etc.  

@benjwadams suspects this is due to database bloat in the PostgreSQL database CKAN uses.  CKAN is configured to store old/expired datasets and other entities in `_history` tables that periodically need to be pruned.

Recommendation is to do a vacuum analyze process on the database, which requires putting it in a locked state, or using pg_repack extension to automate a cleanup process.  

@benjwadams to investigate options for maintaining better routine performance.  If I got any of the above wrong, Ben, please post on the issue thread the approach you take to address it.

**Comment by mwengren** [comment]
@benjwadams We've been getting additional user feedback that the Catalog is performing slowly or giving 404 errors.  

When you're able, could you please look into options for improving performance, including the approach above or other mitigations possible to improve DB performance?   Would increasing the instance size of the DB help, for example?

**Comment by mwengren** [comment]
During today's meeting, Catalog was still having performance issues.  Potentially due to high request volume/traffic incoming from bots or web-scraping jobs.  @benjwadams look into any changes necessary to our request filtering rules to improve performance and reduce overly aggressive request traffic.

**Comment by mwengren** [comment]
Catalog performance looks better, perhaps we can close this?

**Comment by benjwadams** [comment]
CKAN application server has been updated, resulting in much better performance.

`robots.txt` file has been updated to exclude ClaudeBot, which was making a very large number of requests against the server.

**Comment by mwengren** [comment]
Observation over the past few months has shown CKAN to be performing better.  I think we can close this one out!
